// Code generated by ent, DO NOT EDIT.

package alipayorderrollback

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mohaijiang/computeshare-server/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldID, id))
}

// NotifyID applies equality check predicate on the "notify_id" field. It's identical to NotifyIDEQ.
func NotifyID(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyID, v))
}

// NotifyType applies equality check predicate on the "notify_type" field. It's identical to NotifyTypeEQ.
func NotifyType(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyType, v))
}

// NotifyTime applies equality check predicate on the "notify_time" field. It's identical to NotifyTimeEQ.
func NotifyTime(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyTime, v))
}

// Charset applies equality check predicate on the "charset" field. It's identical to CharsetEQ.
func Charset(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldCharset, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldVersion, v))
}

// SignType applies equality check predicate on the "sign_type" field. It's identical to SignTypeEQ.
func SignType(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSignType, v))
}

// Sign applies equality check predicate on the "sign" field. It's identical to SignEQ.
func Sign(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSign, v))
}

// FundBillList applies equality check predicate on the "fund_bill_list" field. It's identical to FundBillListEQ.
func FundBillList(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldFundBillList, v))
}

// ReceiptAmount applies equality check predicate on the "receipt_amount" field. It's identical to ReceiptAmountEQ.
func ReceiptAmount(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldReceiptAmount, v))
}

// InvoiceAmount applies equality check predicate on the "invoice_amount" field. It's identical to InvoiceAmountEQ.
func InvoiceAmount(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldInvoiceAmount, v))
}

// BuyerPayAmount applies equality check predicate on the "buyer_pay_amount" field. It's identical to BuyerPayAmountEQ.
func BuyerPayAmount(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBuyerPayAmount, v))
}

// PointAmount applies equality check predicate on the "point_amount" field. It's identical to PointAmountEQ.
func PointAmount(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldPointAmount, v))
}

// VoucherDetailList applies equality check predicate on the "voucher_detail_list" field. It's identical to VoucherDetailListEQ.
func VoucherDetailList(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldVoucherDetailList, v))
}

// PassbackParams applies equality check predicate on the "passback_params" field. It's identical to PassbackParamsEQ.
func PassbackParams(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldPassbackParams, v))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTradeNo, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldAppID, v))
}

// OutTradeNo applies equality check predicate on the "out_trade_no" field. It's identical to OutTradeNoEQ.
func OutTradeNo(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldOutTradeNo, v))
}

// OutBizNo applies equality check predicate on the "out_biz_no" field. It's identical to OutBizNoEQ.
func OutBizNo(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldOutBizNo, v))
}

// BuyerID applies equality check predicate on the "buyer_id" field. It's identical to BuyerIDEQ.
func BuyerID(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBuyerID, v))
}

// SellerID applies equality check predicate on the "seller_id" field. It's identical to SellerIDEQ.
func SellerID(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSellerID, v))
}

// TradeStatus applies equality check predicate on the "trade_status" field. It's identical to TradeStatusEQ.
func TradeStatus(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTradeStatus, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTotalAmount, v))
}

// RefundFee applies equality check predicate on the "refund_fee" field. It's identical to RefundFeeEQ.
func RefundFee(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldRefundFee, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSubject, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBody, v))
}

// GmtCreate applies equality check predicate on the "gmt_create" field. It's identical to GmtCreateEQ.
func GmtCreate(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtCreate, v))
}

// GmtPayment applies equality check predicate on the "gmt_payment" field. It's identical to GmtPaymentEQ.
func GmtPayment(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtPayment, v))
}

// GmtClose applies equality check predicate on the "gmt_close" field. It's identical to GmtCloseEQ.
func GmtClose(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtClose, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldUpdateTime, v))
}

// NotifyIDEQ applies the EQ predicate on the "notify_id" field.
func NotifyIDEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyID, v))
}

// NotifyIDNEQ applies the NEQ predicate on the "notify_id" field.
func NotifyIDNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldNotifyID, v))
}

// NotifyIDIn applies the In predicate on the "notify_id" field.
func NotifyIDIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldNotifyID, vs...))
}

// NotifyIDNotIn applies the NotIn predicate on the "notify_id" field.
func NotifyIDNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldNotifyID, vs...))
}

// NotifyIDGT applies the GT predicate on the "notify_id" field.
func NotifyIDGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldNotifyID, v))
}

// NotifyIDGTE applies the GTE predicate on the "notify_id" field.
func NotifyIDGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldNotifyID, v))
}

// NotifyIDLT applies the LT predicate on the "notify_id" field.
func NotifyIDLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldNotifyID, v))
}

// NotifyIDLTE applies the LTE predicate on the "notify_id" field.
func NotifyIDLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldNotifyID, v))
}

// NotifyIDContains applies the Contains predicate on the "notify_id" field.
func NotifyIDContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldNotifyID, v))
}

// NotifyIDHasPrefix applies the HasPrefix predicate on the "notify_id" field.
func NotifyIDHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldNotifyID, v))
}

// NotifyIDHasSuffix applies the HasSuffix predicate on the "notify_id" field.
func NotifyIDHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldNotifyID, v))
}

// NotifyIDEqualFold applies the EqualFold predicate on the "notify_id" field.
func NotifyIDEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldNotifyID, v))
}

// NotifyIDContainsFold applies the ContainsFold predicate on the "notify_id" field.
func NotifyIDContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldNotifyID, v))
}

// NotifyTypeEQ applies the EQ predicate on the "notify_type" field.
func NotifyTypeEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyType, v))
}

// NotifyTypeNEQ applies the NEQ predicate on the "notify_type" field.
func NotifyTypeNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldNotifyType, v))
}

// NotifyTypeIn applies the In predicate on the "notify_type" field.
func NotifyTypeIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldNotifyType, vs...))
}

// NotifyTypeNotIn applies the NotIn predicate on the "notify_type" field.
func NotifyTypeNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldNotifyType, vs...))
}

// NotifyTypeGT applies the GT predicate on the "notify_type" field.
func NotifyTypeGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldNotifyType, v))
}

// NotifyTypeGTE applies the GTE predicate on the "notify_type" field.
func NotifyTypeGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldNotifyType, v))
}

// NotifyTypeLT applies the LT predicate on the "notify_type" field.
func NotifyTypeLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldNotifyType, v))
}

// NotifyTypeLTE applies the LTE predicate on the "notify_type" field.
func NotifyTypeLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldNotifyType, v))
}

// NotifyTypeContains applies the Contains predicate on the "notify_type" field.
func NotifyTypeContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldNotifyType, v))
}

// NotifyTypeHasPrefix applies the HasPrefix predicate on the "notify_type" field.
func NotifyTypeHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldNotifyType, v))
}

// NotifyTypeHasSuffix applies the HasSuffix predicate on the "notify_type" field.
func NotifyTypeHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldNotifyType, v))
}

// NotifyTypeEqualFold applies the EqualFold predicate on the "notify_type" field.
func NotifyTypeEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldNotifyType, v))
}

// NotifyTypeContainsFold applies the ContainsFold predicate on the "notify_type" field.
func NotifyTypeContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldNotifyType, v))
}

// NotifyTimeEQ applies the EQ predicate on the "notify_time" field.
func NotifyTimeEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldNotifyTime, v))
}

// NotifyTimeNEQ applies the NEQ predicate on the "notify_time" field.
func NotifyTimeNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldNotifyTime, v))
}

// NotifyTimeIn applies the In predicate on the "notify_time" field.
func NotifyTimeIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldNotifyTime, vs...))
}

// NotifyTimeNotIn applies the NotIn predicate on the "notify_time" field.
func NotifyTimeNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldNotifyTime, vs...))
}

// NotifyTimeGT applies the GT predicate on the "notify_time" field.
func NotifyTimeGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldNotifyTime, v))
}

// NotifyTimeGTE applies the GTE predicate on the "notify_time" field.
func NotifyTimeGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldNotifyTime, v))
}

// NotifyTimeLT applies the LT predicate on the "notify_time" field.
func NotifyTimeLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldNotifyTime, v))
}

// NotifyTimeLTE applies the LTE predicate on the "notify_time" field.
func NotifyTimeLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldNotifyTime, v))
}

// NotifyTimeContains applies the Contains predicate on the "notify_time" field.
func NotifyTimeContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldNotifyTime, v))
}

// NotifyTimeHasPrefix applies the HasPrefix predicate on the "notify_time" field.
func NotifyTimeHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldNotifyTime, v))
}

// NotifyTimeHasSuffix applies the HasSuffix predicate on the "notify_time" field.
func NotifyTimeHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldNotifyTime, v))
}

// NotifyTimeEqualFold applies the EqualFold predicate on the "notify_time" field.
func NotifyTimeEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldNotifyTime, v))
}

// NotifyTimeContainsFold applies the ContainsFold predicate on the "notify_time" field.
func NotifyTimeContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldNotifyTime, v))
}

// CharsetEQ applies the EQ predicate on the "charset" field.
func CharsetEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldCharset, v))
}

// CharsetNEQ applies the NEQ predicate on the "charset" field.
func CharsetNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldCharset, v))
}

// CharsetIn applies the In predicate on the "charset" field.
func CharsetIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldCharset, vs...))
}

// CharsetNotIn applies the NotIn predicate on the "charset" field.
func CharsetNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldCharset, vs...))
}

// CharsetGT applies the GT predicate on the "charset" field.
func CharsetGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldCharset, v))
}

// CharsetGTE applies the GTE predicate on the "charset" field.
func CharsetGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldCharset, v))
}

// CharsetLT applies the LT predicate on the "charset" field.
func CharsetLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldCharset, v))
}

// CharsetLTE applies the LTE predicate on the "charset" field.
func CharsetLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldCharset, v))
}

// CharsetContains applies the Contains predicate on the "charset" field.
func CharsetContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldCharset, v))
}

// CharsetHasPrefix applies the HasPrefix predicate on the "charset" field.
func CharsetHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldCharset, v))
}

// CharsetHasSuffix applies the HasSuffix predicate on the "charset" field.
func CharsetHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldCharset, v))
}

// CharsetEqualFold applies the EqualFold predicate on the "charset" field.
func CharsetEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldCharset, v))
}

// CharsetContainsFold applies the ContainsFold predicate on the "charset" field.
func CharsetContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldCharset, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldVersion, v))
}

// SignTypeEQ applies the EQ predicate on the "sign_type" field.
func SignTypeEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSignType, v))
}

// SignTypeNEQ applies the NEQ predicate on the "sign_type" field.
func SignTypeNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldSignType, v))
}

// SignTypeIn applies the In predicate on the "sign_type" field.
func SignTypeIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldSignType, vs...))
}

// SignTypeNotIn applies the NotIn predicate on the "sign_type" field.
func SignTypeNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldSignType, vs...))
}

// SignTypeGT applies the GT predicate on the "sign_type" field.
func SignTypeGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldSignType, v))
}

// SignTypeGTE applies the GTE predicate on the "sign_type" field.
func SignTypeGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldSignType, v))
}

// SignTypeLT applies the LT predicate on the "sign_type" field.
func SignTypeLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldSignType, v))
}

// SignTypeLTE applies the LTE predicate on the "sign_type" field.
func SignTypeLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldSignType, v))
}

// SignTypeContains applies the Contains predicate on the "sign_type" field.
func SignTypeContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldSignType, v))
}

// SignTypeHasPrefix applies the HasPrefix predicate on the "sign_type" field.
func SignTypeHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldSignType, v))
}

// SignTypeHasSuffix applies the HasSuffix predicate on the "sign_type" field.
func SignTypeHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldSignType, v))
}

// SignTypeEqualFold applies the EqualFold predicate on the "sign_type" field.
func SignTypeEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldSignType, v))
}

// SignTypeContainsFold applies the ContainsFold predicate on the "sign_type" field.
func SignTypeContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldSignType, v))
}

// SignEQ applies the EQ predicate on the "sign" field.
func SignEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSign, v))
}

// SignNEQ applies the NEQ predicate on the "sign" field.
func SignNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldSign, v))
}

// SignIn applies the In predicate on the "sign" field.
func SignIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldSign, vs...))
}

// SignNotIn applies the NotIn predicate on the "sign" field.
func SignNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldSign, vs...))
}

// SignGT applies the GT predicate on the "sign" field.
func SignGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldSign, v))
}

// SignGTE applies the GTE predicate on the "sign" field.
func SignGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldSign, v))
}

// SignLT applies the LT predicate on the "sign" field.
func SignLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldSign, v))
}

// SignLTE applies the LTE predicate on the "sign" field.
func SignLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldSign, v))
}

// SignContains applies the Contains predicate on the "sign" field.
func SignContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldSign, v))
}

// SignHasPrefix applies the HasPrefix predicate on the "sign" field.
func SignHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldSign, v))
}

// SignHasSuffix applies the HasSuffix predicate on the "sign" field.
func SignHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldSign, v))
}

// SignEqualFold applies the EqualFold predicate on the "sign" field.
func SignEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldSign, v))
}

// SignContainsFold applies the ContainsFold predicate on the "sign" field.
func SignContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldSign, v))
}

// FundBillListEQ applies the EQ predicate on the "fund_bill_list" field.
func FundBillListEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldFundBillList, v))
}

// FundBillListNEQ applies the NEQ predicate on the "fund_bill_list" field.
func FundBillListNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldFundBillList, v))
}

// FundBillListIn applies the In predicate on the "fund_bill_list" field.
func FundBillListIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldFundBillList, vs...))
}

// FundBillListNotIn applies the NotIn predicate on the "fund_bill_list" field.
func FundBillListNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldFundBillList, vs...))
}

// FundBillListGT applies the GT predicate on the "fund_bill_list" field.
func FundBillListGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldFundBillList, v))
}

// FundBillListGTE applies the GTE predicate on the "fund_bill_list" field.
func FundBillListGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldFundBillList, v))
}

// FundBillListLT applies the LT predicate on the "fund_bill_list" field.
func FundBillListLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldFundBillList, v))
}

// FundBillListLTE applies the LTE predicate on the "fund_bill_list" field.
func FundBillListLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldFundBillList, v))
}

// FundBillListContains applies the Contains predicate on the "fund_bill_list" field.
func FundBillListContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldFundBillList, v))
}

// FundBillListHasPrefix applies the HasPrefix predicate on the "fund_bill_list" field.
func FundBillListHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldFundBillList, v))
}

// FundBillListHasSuffix applies the HasSuffix predicate on the "fund_bill_list" field.
func FundBillListHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldFundBillList, v))
}

// FundBillListEqualFold applies the EqualFold predicate on the "fund_bill_list" field.
func FundBillListEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldFundBillList, v))
}

// FundBillListContainsFold applies the ContainsFold predicate on the "fund_bill_list" field.
func FundBillListContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldFundBillList, v))
}

// ReceiptAmountEQ applies the EQ predicate on the "receipt_amount" field.
func ReceiptAmountEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldReceiptAmount, v))
}

// ReceiptAmountNEQ applies the NEQ predicate on the "receipt_amount" field.
func ReceiptAmountNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldReceiptAmount, v))
}

// ReceiptAmountIn applies the In predicate on the "receipt_amount" field.
func ReceiptAmountIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldReceiptAmount, vs...))
}

// ReceiptAmountNotIn applies the NotIn predicate on the "receipt_amount" field.
func ReceiptAmountNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldReceiptAmount, vs...))
}

// ReceiptAmountGT applies the GT predicate on the "receipt_amount" field.
func ReceiptAmountGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldReceiptAmount, v))
}

// ReceiptAmountGTE applies the GTE predicate on the "receipt_amount" field.
func ReceiptAmountGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldReceiptAmount, v))
}

// ReceiptAmountLT applies the LT predicate on the "receipt_amount" field.
func ReceiptAmountLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldReceiptAmount, v))
}

// ReceiptAmountLTE applies the LTE predicate on the "receipt_amount" field.
func ReceiptAmountLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldReceiptAmount, v))
}

// ReceiptAmountContains applies the Contains predicate on the "receipt_amount" field.
func ReceiptAmountContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldReceiptAmount, v))
}

// ReceiptAmountHasPrefix applies the HasPrefix predicate on the "receipt_amount" field.
func ReceiptAmountHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldReceiptAmount, v))
}

// ReceiptAmountHasSuffix applies the HasSuffix predicate on the "receipt_amount" field.
func ReceiptAmountHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldReceiptAmount, v))
}

// ReceiptAmountEqualFold applies the EqualFold predicate on the "receipt_amount" field.
func ReceiptAmountEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldReceiptAmount, v))
}

// ReceiptAmountContainsFold applies the ContainsFold predicate on the "receipt_amount" field.
func ReceiptAmountContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldReceiptAmount, v))
}

// InvoiceAmountEQ applies the EQ predicate on the "invoice_amount" field.
func InvoiceAmountEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountNEQ applies the NEQ predicate on the "invoice_amount" field.
func InvoiceAmountNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountIn applies the In predicate on the "invoice_amount" field.
func InvoiceAmountIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountNotIn applies the NotIn predicate on the "invoice_amount" field.
func InvoiceAmountNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountGT applies the GT predicate on the "invoice_amount" field.
func InvoiceAmountGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldInvoiceAmount, v))
}

// InvoiceAmountGTE applies the GTE predicate on the "invoice_amount" field.
func InvoiceAmountGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldInvoiceAmount, v))
}

// InvoiceAmountLT applies the LT predicate on the "invoice_amount" field.
func InvoiceAmountLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldInvoiceAmount, v))
}

// InvoiceAmountLTE applies the LTE predicate on the "invoice_amount" field.
func InvoiceAmountLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldInvoiceAmount, v))
}

// InvoiceAmountContains applies the Contains predicate on the "invoice_amount" field.
func InvoiceAmountContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldInvoiceAmount, v))
}

// InvoiceAmountHasPrefix applies the HasPrefix predicate on the "invoice_amount" field.
func InvoiceAmountHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldInvoiceAmount, v))
}

// InvoiceAmountHasSuffix applies the HasSuffix predicate on the "invoice_amount" field.
func InvoiceAmountHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldInvoiceAmount, v))
}

// InvoiceAmountEqualFold applies the EqualFold predicate on the "invoice_amount" field.
func InvoiceAmountEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldInvoiceAmount, v))
}

// InvoiceAmountContainsFold applies the ContainsFold predicate on the "invoice_amount" field.
func InvoiceAmountContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldInvoiceAmount, v))
}

// BuyerPayAmountEQ applies the EQ predicate on the "buyer_pay_amount" field.
func BuyerPayAmountEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBuyerPayAmount, v))
}

// BuyerPayAmountNEQ applies the NEQ predicate on the "buyer_pay_amount" field.
func BuyerPayAmountNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldBuyerPayAmount, v))
}

// BuyerPayAmountIn applies the In predicate on the "buyer_pay_amount" field.
func BuyerPayAmountIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldBuyerPayAmount, vs...))
}

// BuyerPayAmountNotIn applies the NotIn predicate on the "buyer_pay_amount" field.
func BuyerPayAmountNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldBuyerPayAmount, vs...))
}

// BuyerPayAmountGT applies the GT predicate on the "buyer_pay_amount" field.
func BuyerPayAmountGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldBuyerPayAmount, v))
}

// BuyerPayAmountGTE applies the GTE predicate on the "buyer_pay_amount" field.
func BuyerPayAmountGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldBuyerPayAmount, v))
}

// BuyerPayAmountLT applies the LT predicate on the "buyer_pay_amount" field.
func BuyerPayAmountLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldBuyerPayAmount, v))
}

// BuyerPayAmountLTE applies the LTE predicate on the "buyer_pay_amount" field.
func BuyerPayAmountLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldBuyerPayAmount, v))
}

// BuyerPayAmountContains applies the Contains predicate on the "buyer_pay_amount" field.
func BuyerPayAmountContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldBuyerPayAmount, v))
}

// BuyerPayAmountHasPrefix applies the HasPrefix predicate on the "buyer_pay_amount" field.
func BuyerPayAmountHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldBuyerPayAmount, v))
}

// BuyerPayAmountHasSuffix applies the HasSuffix predicate on the "buyer_pay_amount" field.
func BuyerPayAmountHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldBuyerPayAmount, v))
}

// BuyerPayAmountEqualFold applies the EqualFold predicate on the "buyer_pay_amount" field.
func BuyerPayAmountEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldBuyerPayAmount, v))
}

// BuyerPayAmountContainsFold applies the ContainsFold predicate on the "buyer_pay_amount" field.
func BuyerPayAmountContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldBuyerPayAmount, v))
}

// PointAmountEQ applies the EQ predicate on the "point_amount" field.
func PointAmountEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldPointAmount, v))
}

// PointAmountNEQ applies the NEQ predicate on the "point_amount" field.
func PointAmountNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldPointAmount, v))
}

// PointAmountIn applies the In predicate on the "point_amount" field.
func PointAmountIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldPointAmount, vs...))
}

// PointAmountNotIn applies the NotIn predicate on the "point_amount" field.
func PointAmountNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldPointAmount, vs...))
}

// PointAmountGT applies the GT predicate on the "point_amount" field.
func PointAmountGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldPointAmount, v))
}

// PointAmountGTE applies the GTE predicate on the "point_amount" field.
func PointAmountGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldPointAmount, v))
}

// PointAmountLT applies the LT predicate on the "point_amount" field.
func PointAmountLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldPointAmount, v))
}

// PointAmountLTE applies the LTE predicate on the "point_amount" field.
func PointAmountLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldPointAmount, v))
}

// PointAmountContains applies the Contains predicate on the "point_amount" field.
func PointAmountContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldPointAmount, v))
}

// PointAmountHasPrefix applies the HasPrefix predicate on the "point_amount" field.
func PointAmountHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldPointAmount, v))
}

// PointAmountHasSuffix applies the HasSuffix predicate on the "point_amount" field.
func PointAmountHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldPointAmount, v))
}

// PointAmountEqualFold applies the EqualFold predicate on the "point_amount" field.
func PointAmountEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldPointAmount, v))
}

// PointAmountContainsFold applies the ContainsFold predicate on the "point_amount" field.
func PointAmountContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldPointAmount, v))
}

// VoucherDetailListEQ applies the EQ predicate on the "voucher_detail_list" field.
func VoucherDetailListEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldVoucherDetailList, v))
}

// VoucherDetailListNEQ applies the NEQ predicate on the "voucher_detail_list" field.
func VoucherDetailListNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldVoucherDetailList, v))
}

// VoucherDetailListIn applies the In predicate on the "voucher_detail_list" field.
func VoucherDetailListIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldVoucherDetailList, vs...))
}

// VoucherDetailListNotIn applies the NotIn predicate on the "voucher_detail_list" field.
func VoucherDetailListNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldVoucherDetailList, vs...))
}

// VoucherDetailListGT applies the GT predicate on the "voucher_detail_list" field.
func VoucherDetailListGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldVoucherDetailList, v))
}

// VoucherDetailListGTE applies the GTE predicate on the "voucher_detail_list" field.
func VoucherDetailListGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldVoucherDetailList, v))
}

// VoucherDetailListLT applies the LT predicate on the "voucher_detail_list" field.
func VoucherDetailListLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldVoucherDetailList, v))
}

// VoucherDetailListLTE applies the LTE predicate on the "voucher_detail_list" field.
func VoucherDetailListLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldVoucherDetailList, v))
}

// VoucherDetailListContains applies the Contains predicate on the "voucher_detail_list" field.
func VoucherDetailListContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldVoucherDetailList, v))
}

// VoucherDetailListHasPrefix applies the HasPrefix predicate on the "voucher_detail_list" field.
func VoucherDetailListHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldVoucherDetailList, v))
}

// VoucherDetailListHasSuffix applies the HasSuffix predicate on the "voucher_detail_list" field.
func VoucherDetailListHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldVoucherDetailList, v))
}

// VoucherDetailListEqualFold applies the EqualFold predicate on the "voucher_detail_list" field.
func VoucherDetailListEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldVoucherDetailList, v))
}

// VoucherDetailListContainsFold applies the ContainsFold predicate on the "voucher_detail_list" field.
func VoucherDetailListContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldVoucherDetailList, v))
}

// PassbackParamsEQ applies the EQ predicate on the "passback_params" field.
func PassbackParamsEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldPassbackParams, v))
}

// PassbackParamsNEQ applies the NEQ predicate on the "passback_params" field.
func PassbackParamsNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldPassbackParams, v))
}

// PassbackParamsIn applies the In predicate on the "passback_params" field.
func PassbackParamsIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldPassbackParams, vs...))
}

// PassbackParamsNotIn applies the NotIn predicate on the "passback_params" field.
func PassbackParamsNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldPassbackParams, vs...))
}

// PassbackParamsGT applies the GT predicate on the "passback_params" field.
func PassbackParamsGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldPassbackParams, v))
}

// PassbackParamsGTE applies the GTE predicate on the "passback_params" field.
func PassbackParamsGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldPassbackParams, v))
}

// PassbackParamsLT applies the LT predicate on the "passback_params" field.
func PassbackParamsLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldPassbackParams, v))
}

// PassbackParamsLTE applies the LTE predicate on the "passback_params" field.
func PassbackParamsLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldPassbackParams, v))
}

// PassbackParamsContains applies the Contains predicate on the "passback_params" field.
func PassbackParamsContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldPassbackParams, v))
}

// PassbackParamsHasPrefix applies the HasPrefix predicate on the "passback_params" field.
func PassbackParamsHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldPassbackParams, v))
}

// PassbackParamsHasSuffix applies the HasSuffix predicate on the "passback_params" field.
func PassbackParamsHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldPassbackParams, v))
}

// PassbackParamsEqualFold applies the EqualFold predicate on the "passback_params" field.
func PassbackParamsEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldPassbackParams, v))
}

// PassbackParamsContainsFold applies the ContainsFold predicate on the "passback_params" field.
func PassbackParamsContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldPassbackParams, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldTradeNo, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldAppID, v))
}

// OutTradeNoEQ applies the EQ predicate on the "out_trade_no" field.
func OutTradeNoEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldOutTradeNo, v))
}

// OutTradeNoNEQ applies the NEQ predicate on the "out_trade_no" field.
func OutTradeNoNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldOutTradeNo, v))
}

// OutTradeNoIn applies the In predicate on the "out_trade_no" field.
func OutTradeNoIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldOutTradeNo, vs...))
}

// OutTradeNoNotIn applies the NotIn predicate on the "out_trade_no" field.
func OutTradeNoNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldOutTradeNo, vs...))
}

// OutTradeNoGT applies the GT predicate on the "out_trade_no" field.
func OutTradeNoGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldOutTradeNo, v))
}

// OutTradeNoGTE applies the GTE predicate on the "out_trade_no" field.
func OutTradeNoGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldOutTradeNo, v))
}

// OutTradeNoLT applies the LT predicate on the "out_trade_no" field.
func OutTradeNoLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldOutTradeNo, v))
}

// OutTradeNoLTE applies the LTE predicate on the "out_trade_no" field.
func OutTradeNoLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldOutTradeNo, v))
}

// OutTradeNoContains applies the Contains predicate on the "out_trade_no" field.
func OutTradeNoContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldOutTradeNo, v))
}

// OutTradeNoHasPrefix applies the HasPrefix predicate on the "out_trade_no" field.
func OutTradeNoHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldOutTradeNo, v))
}

// OutTradeNoHasSuffix applies the HasSuffix predicate on the "out_trade_no" field.
func OutTradeNoHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldOutTradeNo, v))
}

// OutTradeNoEqualFold applies the EqualFold predicate on the "out_trade_no" field.
func OutTradeNoEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldOutTradeNo, v))
}

// OutTradeNoContainsFold applies the ContainsFold predicate on the "out_trade_no" field.
func OutTradeNoContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldOutTradeNo, v))
}

// OutBizNoEQ applies the EQ predicate on the "out_biz_no" field.
func OutBizNoEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldOutBizNo, v))
}

// OutBizNoNEQ applies the NEQ predicate on the "out_biz_no" field.
func OutBizNoNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldOutBizNo, v))
}

// OutBizNoIn applies the In predicate on the "out_biz_no" field.
func OutBizNoIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldOutBizNo, vs...))
}

// OutBizNoNotIn applies the NotIn predicate on the "out_biz_no" field.
func OutBizNoNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldOutBizNo, vs...))
}

// OutBizNoGT applies the GT predicate on the "out_biz_no" field.
func OutBizNoGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldOutBizNo, v))
}

// OutBizNoGTE applies the GTE predicate on the "out_biz_no" field.
func OutBizNoGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldOutBizNo, v))
}

// OutBizNoLT applies the LT predicate on the "out_biz_no" field.
func OutBizNoLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldOutBizNo, v))
}

// OutBizNoLTE applies the LTE predicate on the "out_biz_no" field.
func OutBizNoLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldOutBizNo, v))
}

// OutBizNoContains applies the Contains predicate on the "out_biz_no" field.
func OutBizNoContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldOutBizNo, v))
}

// OutBizNoHasPrefix applies the HasPrefix predicate on the "out_biz_no" field.
func OutBizNoHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldOutBizNo, v))
}

// OutBizNoHasSuffix applies the HasSuffix predicate on the "out_biz_no" field.
func OutBizNoHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldOutBizNo, v))
}

// OutBizNoEqualFold applies the EqualFold predicate on the "out_biz_no" field.
func OutBizNoEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldOutBizNo, v))
}

// OutBizNoContainsFold applies the ContainsFold predicate on the "out_biz_no" field.
func OutBizNoContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldOutBizNo, v))
}

// BuyerIDEQ applies the EQ predicate on the "buyer_id" field.
func BuyerIDEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBuyerID, v))
}

// BuyerIDNEQ applies the NEQ predicate on the "buyer_id" field.
func BuyerIDNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldBuyerID, v))
}

// BuyerIDIn applies the In predicate on the "buyer_id" field.
func BuyerIDIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldBuyerID, vs...))
}

// BuyerIDNotIn applies the NotIn predicate on the "buyer_id" field.
func BuyerIDNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldBuyerID, vs...))
}

// BuyerIDGT applies the GT predicate on the "buyer_id" field.
func BuyerIDGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldBuyerID, v))
}

// BuyerIDGTE applies the GTE predicate on the "buyer_id" field.
func BuyerIDGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldBuyerID, v))
}

// BuyerIDLT applies the LT predicate on the "buyer_id" field.
func BuyerIDLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldBuyerID, v))
}

// BuyerIDLTE applies the LTE predicate on the "buyer_id" field.
func BuyerIDLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldBuyerID, v))
}

// BuyerIDContains applies the Contains predicate on the "buyer_id" field.
func BuyerIDContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldBuyerID, v))
}

// BuyerIDHasPrefix applies the HasPrefix predicate on the "buyer_id" field.
func BuyerIDHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldBuyerID, v))
}

// BuyerIDHasSuffix applies the HasSuffix predicate on the "buyer_id" field.
func BuyerIDHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldBuyerID, v))
}

// BuyerIDEqualFold applies the EqualFold predicate on the "buyer_id" field.
func BuyerIDEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldBuyerID, v))
}

// BuyerIDContainsFold applies the ContainsFold predicate on the "buyer_id" field.
func BuyerIDContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldBuyerID, v))
}

// SellerIDEQ applies the EQ predicate on the "seller_id" field.
func SellerIDEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSellerID, v))
}

// SellerIDNEQ applies the NEQ predicate on the "seller_id" field.
func SellerIDNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldSellerID, v))
}

// SellerIDIn applies the In predicate on the "seller_id" field.
func SellerIDIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldSellerID, vs...))
}

// SellerIDNotIn applies the NotIn predicate on the "seller_id" field.
func SellerIDNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldSellerID, vs...))
}

// SellerIDGT applies the GT predicate on the "seller_id" field.
func SellerIDGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldSellerID, v))
}

// SellerIDGTE applies the GTE predicate on the "seller_id" field.
func SellerIDGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldSellerID, v))
}

// SellerIDLT applies the LT predicate on the "seller_id" field.
func SellerIDLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldSellerID, v))
}

// SellerIDLTE applies the LTE predicate on the "seller_id" field.
func SellerIDLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldSellerID, v))
}

// SellerIDContains applies the Contains predicate on the "seller_id" field.
func SellerIDContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldSellerID, v))
}

// SellerIDHasPrefix applies the HasPrefix predicate on the "seller_id" field.
func SellerIDHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldSellerID, v))
}

// SellerIDHasSuffix applies the HasSuffix predicate on the "seller_id" field.
func SellerIDHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldSellerID, v))
}

// SellerIDEqualFold applies the EqualFold predicate on the "seller_id" field.
func SellerIDEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldSellerID, v))
}

// SellerIDContainsFold applies the ContainsFold predicate on the "seller_id" field.
func SellerIDContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldSellerID, v))
}

// TradeStatusEQ applies the EQ predicate on the "trade_status" field.
func TradeStatusEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTradeStatus, v))
}

// TradeStatusNEQ applies the NEQ predicate on the "trade_status" field.
func TradeStatusNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldTradeStatus, v))
}

// TradeStatusIn applies the In predicate on the "trade_status" field.
func TradeStatusIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldTradeStatus, vs...))
}

// TradeStatusNotIn applies the NotIn predicate on the "trade_status" field.
func TradeStatusNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldTradeStatus, vs...))
}

// TradeStatusGT applies the GT predicate on the "trade_status" field.
func TradeStatusGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldTradeStatus, v))
}

// TradeStatusGTE applies the GTE predicate on the "trade_status" field.
func TradeStatusGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldTradeStatus, v))
}

// TradeStatusLT applies the LT predicate on the "trade_status" field.
func TradeStatusLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldTradeStatus, v))
}

// TradeStatusLTE applies the LTE predicate on the "trade_status" field.
func TradeStatusLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldTradeStatus, v))
}

// TradeStatusContains applies the Contains predicate on the "trade_status" field.
func TradeStatusContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldTradeStatus, v))
}

// TradeStatusHasPrefix applies the HasPrefix predicate on the "trade_status" field.
func TradeStatusHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldTradeStatus, v))
}

// TradeStatusHasSuffix applies the HasSuffix predicate on the "trade_status" field.
func TradeStatusHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldTradeStatus, v))
}

// TradeStatusEqualFold applies the EqualFold predicate on the "trade_status" field.
func TradeStatusEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldTradeStatus, v))
}

// TradeStatusContainsFold applies the ContainsFold predicate on the "trade_status" field.
func TradeStatusContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldTradeStatus, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldTotalAmount, v))
}

// TotalAmountContains applies the Contains predicate on the "total_amount" field.
func TotalAmountContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldTotalAmount, v))
}

// TotalAmountHasPrefix applies the HasPrefix predicate on the "total_amount" field.
func TotalAmountHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldTotalAmount, v))
}

// TotalAmountHasSuffix applies the HasSuffix predicate on the "total_amount" field.
func TotalAmountHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldTotalAmount, v))
}

// TotalAmountEqualFold applies the EqualFold predicate on the "total_amount" field.
func TotalAmountEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldTotalAmount, v))
}

// TotalAmountContainsFold applies the ContainsFold predicate on the "total_amount" field.
func TotalAmountContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldTotalAmount, v))
}

// RefundFeeEQ applies the EQ predicate on the "refund_fee" field.
func RefundFeeEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldRefundFee, v))
}

// RefundFeeNEQ applies the NEQ predicate on the "refund_fee" field.
func RefundFeeNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldRefundFee, v))
}

// RefundFeeIn applies the In predicate on the "refund_fee" field.
func RefundFeeIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldRefundFee, vs...))
}

// RefundFeeNotIn applies the NotIn predicate on the "refund_fee" field.
func RefundFeeNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldRefundFee, vs...))
}

// RefundFeeGT applies the GT predicate on the "refund_fee" field.
func RefundFeeGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldRefundFee, v))
}

// RefundFeeGTE applies the GTE predicate on the "refund_fee" field.
func RefundFeeGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldRefundFee, v))
}

// RefundFeeLT applies the LT predicate on the "refund_fee" field.
func RefundFeeLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldRefundFee, v))
}

// RefundFeeLTE applies the LTE predicate on the "refund_fee" field.
func RefundFeeLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldRefundFee, v))
}

// RefundFeeContains applies the Contains predicate on the "refund_fee" field.
func RefundFeeContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldRefundFee, v))
}

// RefundFeeHasPrefix applies the HasPrefix predicate on the "refund_fee" field.
func RefundFeeHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldRefundFee, v))
}

// RefundFeeHasSuffix applies the HasSuffix predicate on the "refund_fee" field.
func RefundFeeHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldRefundFee, v))
}

// RefundFeeEqualFold applies the EqualFold predicate on the "refund_fee" field.
func RefundFeeEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldRefundFee, v))
}

// RefundFeeContainsFold applies the ContainsFold predicate on the "refund_fee" field.
func RefundFeeContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldRefundFee, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldSubject, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldBody, v))
}

// GmtCreateEQ applies the EQ predicate on the "gmt_create" field.
func GmtCreateEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtCreate, v))
}

// GmtCreateNEQ applies the NEQ predicate on the "gmt_create" field.
func GmtCreateNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldGmtCreate, v))
}

// GmtCreateIn applies the In predicate on the "gmt_create" field.
func GmtCreateIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldGmtCreate, vs...))
}

// GmtCreateNotIn applies the NotIn predicate on the "gmt_create" field.
func GmtCreateNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldGmtCreate, vs...))
}

// GmtCreateGT applies the GT predicate on the "gmt_create" field.
func GmtCreateGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldGmtCreate, v))
}

// GmtCreateGTE applies the GTE predicate on the "gmt_create" field.
func GmtCreateGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldGmtCreate, v))
}

// GmtCreateLT applies the LT predicate on the "gmt_create" field.
func GmtCreateLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldGmtCreate, v))
}

// GmtCreateLTE applies the LTE predicate on the "gmt_create" field.
func GmtCreateLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldGmtCreate, v))
}

// GmtCreateContains applies the Contains predicate on the "gmt_create" field.
func GmtCreateContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldGmtCreate, v))
}

// GmtCreateHasPrefix applies the HasPrefix predicate on the "gmt_create" field.
func GmtCreateHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldGmtCreate, v))
}

// GmtCreateHasSuffix applies the HasSuffix predicate on the "gmt_create" field.
func GmtCreateHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldGmtCreate, v))
}

// GmtCreateEqualFold applies the EqualFold predicate on the "gmt_create" field.
func GmtCreateEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldGmtCreate, v))
}

// GmtCreateContainsFold applies the ContainsFold predicate on the "gmt_create" field.
func GmtCreateContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldGmtCreate, v))
}

// GmtPaymentEQ applies the EQ predicate on the "gmt_payment" field.
func GmtPaymentEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtPayment, v))
}

// GmtPaymentNEQ applies the NEQ predicate on the "gmt_payment" field.
func GmtPaymentNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldGmtPayment, v))
}

// GmtPaymentIn applies the In predicate on the "gmt_payment" field.
func GmtPaymentIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldGmtPayment, vs...))
}

// GmtPaymentNotIn applies the NotIn predicate on the "gmt_payment" field.
func GmtPaymentNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldGmtPayment, vs...))
}

// GmtPaymentGT applies the GT predicate on the "gmt_payment" field.
func GmtPaymentGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldGmtPayment, v))
}

// GmtPaymentGTE applies the GTE predicate on the "gmt_payment" field.
func GmtPaymentGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldGmtPayment, v))
}

// GmtPaymentLT applies the LT predicate on the "gmt_payment" field.
func GmtPaymentLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldGmtPayment, v))
}

// GmtPaymentLTE applies the LTE predicate on the "gmt_payment" field.
func GmtPaymentLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldGmtPayment, v))
}

// GmtPaymentContains applies the Contains predicate on the "gmt_payment" field.
func GmtPaymentContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldGmtPayment, v))
}

// GmtPaymentHasPrefix applies the HasPrefix predicate on the "gmt_payment" field.
func GmtPaymentHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldGmtPayment, v))
}

// GmtPaymentHasSuffix applies the HasSuffix predicate on the "gmt_payment" field.
func GmtPaymentHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldGmtPayment, v))
}

// GmtPaymentEqualFold applies the EqualFold predicate on the "gmt_payment" field.
func GmtPaymentEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldGmtPayment, v))
}

// GmtPaymentContainsFold applies the ContainsFold predicate on the "gmt_payment" field.
func GmtPaymentContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldGmtPayment, v))
}

// GmtCloseEQ applies the EQ predicate on the "gmt_close" field.
func GmtCloseEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldGmtClose, v))
}

// GmtCloseNEQ applies the NEQ predicate on the "gmt_close" field.
func GmtCloseNEQ(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldGmtClose, v))
}

// GmtCloseIn applies the In predicate on the "gmt_close" field.
func GmtCloseIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldGmtClose, vs...))
}

// GmtCloseNotIn applies the NotIn predicate on the "gmt_close" field.
func GmtCloseNotIn(vs ...string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldGmtClose, vs...))
}

// GmtCloseGT applies the GT predicate on the "gmt_close" field.
func GmtCloseGT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldGmtClose, v))
}

// GmtCloseGTE applies the GTE predicate on the "gmt_close" field.
func GmtCloseGTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldGmtClose, v))
}

// GmtCloseLT applies the LT predicate on the "gmt_close" field.
func GmtCloseLT(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldGmtClose, v))
}

// GmtCloseLTE applies the LTE predicate on the "gmt_close" field.
func GmtCloseLTE(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldGmtClose, v))
}

// GmtCloseContains applies the Contains predicate on the "gmt_close" field.
func GmtCloseContains(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContains(FieldGmtClose, v))
}

// GmtCloseHasPrefix applies the HasPrefix predicate on the "gmt_close" field.
func GmtCloseHasPrefix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasPrefix(FieldGmtClose, v))
}

// GmtCloseHasSuffix applies the HasSuffix predicate on the "gmt_close" field.
func GmtCloseHasSuffix(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldHasSuffix(FieldGmtClose, v))
}

// GmtCloseEqualFold applies the EqualFold predicate on the "gmt_close" field.
func GmtCloseEqualFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEqualFold(FieldGmtClose, v))
}

// GmtCloseContainsFold applies the ContainsFold predicate on the "gmt_close" field.
func GmtCloseContainsFold(v string) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldContainsFold(FieldGmtClose, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlipayOrderRollback) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlipayOrderRollback) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlipayOrderRollback) predicate.AlipayOrderRollback {
	return predicate.AlipayOrderRollback(func(s *sql.Selector) {
		p(s.Not())
	})
}
