// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: server/compute/v1/storage_s3.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateS3KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateS3KeyRequest) Reset() {
	*x = CreateS3KeyRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateS3KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateS3KeyRequest) ProtoMessage() {}

func (x *CreateS3KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateS3KeyRequest.ProtoReflect.Descriptor instead.
func (*CreateS3KeyRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{0}
}

type CreateS3KeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateS3KeyReply) Reset() {
	*x = CreateS3KeyReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateS3KeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateS3KeyReply) ProtoMessage() {}

func (x *CreateS3KeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateS3KeyReply.ProtoReflect.Descriptor instead.
func (*CreateS3KeyReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{1}
}

func (x *CreateS3KeyReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateS3KeyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type S3User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessKey     string                 `protobuf:"bytes,2,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3User) Reset() {
	*x = S3User{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3User) ProtoMessage() {}

func (x *S3User) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3User.ProtoReflect.Descriptor instead.
func (*S3User) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{2}
}

func (x *S3User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *S3User) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3User) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *S3User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *S3User) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *S3User) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type GetUserS3UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserS3UserListRequest) Reset() {
	*x = GetUserS3UserListRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserS3UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserS3UserListRequest) ProtoMessage() {}

func (x *GetUserS3UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserS3UserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserS3UserListRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{3}
}

type GetUserS3UserListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*S3User              `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserS3UserListReply) Reset() {
	*x = GetUserS3UserListReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserS3UserListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserS3UserListReply) ProtoMessage() {}

func (x *GetUserS3UserListReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserS3UserListReply.ProtoReflect.Descriptor instead.
func (*GetUserS3UserListReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserS3UserListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserS3UserListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserS3UserListReply) GetData() []*S3User {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserS3UserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryCallCoding string                 `protobuf:"bytes,2,opt,name=countryCallCoding,proto3" json:"countryCallCoding,omitempty"`
	TelephoneNumber   string                 `protobuf:"bytes,3,opt,name=telephoneNumber,proto3" json:"telephoneNumber,omitempty"`
	ValidateCode      string                 `protobuf:"bytes,4,opt,name=validateCode,proto3" json:"validateCode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserS3UserRequest) Reset() {
	*x = GetUserS3UserRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserS3UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserS3UserRequest) ProtoMessage() {}

func (x *GetUserS3UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserS3UserRequest.ProtoReflect.Descriptor instead.
func (*GetUserS3UserRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserS3UserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserS3UserRequest) GetCountryCallCoding() string {
	if x != nil {
		return x.CountryCallCoding
	}
	return ""
}

func (x *GetUserS3UserRequest) GetTelephoneNumber() string {
	if x != nil {
		return x.TelephoneNumber
	}
	return ""
}

func (x *GetUserS3UserRequest) GetValidateCode() string {
	if x != nil {
		return x.ValidateCode
	}
	return ""
}

type GetUserS3UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *S3User                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserS3UserReply) Reset() {
	*x = GetUserS3UserReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserS3UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserS3UserReply) ProtoMessage() {}

func (x *GetUserS3UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserS3UserReply.ProtoReflect.Descriptor instead.
func (*GetUserS3UserReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserS3UserReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserS3UserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserS3UserReply) GetData() *S3User {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteUserS3UserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryCallCoding string                 `protobuf:"bytes,2,opt,name=countryCallCoding,proto3" json:"countryCallCoding,omitempty"`
	TelephoneNumber   string                 `protobuf:"bytes,3,opt,name=telephoneNumber,proto3" json:"telephoneNumber,omitempty"`
	ValidateCode      string                 `protobuf:"bytes,4,opt,name=validateCode,proto3" json:"validateCode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteUserS3UserRequest) Reset() {
	*x = DeleteUserS3UserRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserS3UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserS3UserRequest) ProtoMessage() {}

func (x *DeleteUserS3UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserS3UserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserS3UserRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserS3UserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteUserS3UserRequest) GetCountryCallCoding() string {
	if x != nil {
		return x.CountryCallCoding
	}
	return ""
}

func (x *DeleteUserS3UserRequest) GetTelephoneNumber() string {
	if x != nil {
		return x.TelephoneNumber
	}
	return ""
}

func (x *DeleteUserS3UserRequest) GetValidateCode() string {
	if x != nil {
		return x.ValidateCode
	}
	return ""
}

type DeleteUserS3UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserS3UserReply) Reset() {
	*x = DeleteUserS3UserReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserS3UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserS3UserReply) ProtoMessage() {}

func (x *DeleteUserS3UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserS3UserReply.ProtoReflect.Descriptor instead.
func (*DeleteUserS3UserReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserS3UserReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteUserS3UserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type CreateBucketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // bucket id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketReply) Reset() {
	*x = CreateBucketReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketReply) ProtoMessage() {}

func (x *CreateBucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketReply.ProtoReflect.Descriptor instead.
func (*CreateBucketReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBucketReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateBucketReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBucketReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type DeleteBucketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketReply) Reset() {
	*x = DeleteBucketReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketReply) ProtoMessage() {}

func (x *DeleteBucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketReply.ProtoReflect.Descriptor instead.
func (*DeleteBucketReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBucketReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteBucketReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyBucketRequest) Reset() {
	*x = EmptyBucketRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyBucketRequest) ProtoMessage() {}

func (x *EmptyBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyBucketRequest.ProtoReflect.Descriptor instead.
func (*EmptyBucketRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{13}
}

func (x *EmptyBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type EmptyBucketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyBucketReply) Reset() {
	*x = EmptyBucketReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyBucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyBucketReply) ProtoMessage() {}

func (x *EmptyBucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyBucketReply.ProtoReflect.Descriptor instead.
func (*EmptyBucketReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{14}
}

func (x *EmptyBucketReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyBucketReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketRequest) Reset() {
	*x = ListBucketRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketRequest) ProtoMessage() {}

func (x *ListBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketRequest.ProtoReflect.Descriptor instead.
func (*ListBucketRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{15}
}

func (x *ListBucketRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBucketRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListBucketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListBucketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ListBucketReply_Data  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketReply) Reset() {
	*x = ListBucketReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketReply) ProtoMessage() {}

func (x *ListBucketReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketReply.ProtoReflect.Descriptor instead.
func (*ListBucketReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{16}
}

func (x *ListBucketReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListBucketReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListBucketReply) GetData() *ListBucketReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type S3Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	S3Url         string                 `protobuf:"bytes,4,opt,name=s3Url,proto3" json:"s3Url,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Size          int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	LastModify    int64                  `protobuf:"varint,7,opt,name=last_modify,json=lastModify,proto3" json:"last_modify,omitempty"`
	Prefix        string                 `protobuf:"bytes,8,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Object) Reset() {
	*x = S3Object{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Object) ProtoMessage() {}

func (x *S3Object) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Object.ProtoReflect.Descriptor instead.
func (*S3Object) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{17}
}

func (x *S3Object) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *S3Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *S3Object) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

func (x *S3Object) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *S3Object) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *S3Object) GetLastModify() int64 {
	if x != nil {
		return x.LastModify
	}
	return 0
}

func (x *S3Object) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type S3StorageInBucketListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageInBucketListRequest) Reset() {
	*x = S3StorageInBucketListRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageInBucketListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageInBucketListRequest) ProtoMessage() {}

func (x *S3StorageInBucketListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageInBucketListRequest.ProtoReflect.Descriptor instead.
func (*S3StorageInBucketListRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{18}
}

func (x *S3StorageInBucketListRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3StorageInBucketListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *S3StorageInBucketListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *S3StorageInBucketListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *S3StorageInBucketListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type S3StorageInBucketListReply struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Code          int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *S3StorageInBucketListReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageInBucketListReply) Reset() {
	*x = S3StorageInBucketListReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageInBucketListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageInBucketListReply) ProtoMessage() {}

func (x *S3StorageInBucketListReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageInBucketListReply.ProtoReflect.Descriptor instead.
func (*S3StorageInBucketListReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{19}
}

func (x *S3StorageInBucketListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageInBucketListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S3StorageInBucketListReply) GetData() *S3StorageInBucketListReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type S3StorageMkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	DirName       string                 `protobuf:"bytes,2,opt,name=dirName,proto3" json:"dirName,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageMkdirRequest) Reset() {
	*x = S3StorageMkdirRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageMkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageMkdirRequest) ProtoMessage() {}

func (x *S3StorageMkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageMkdirRequest.ProtoReflect.Descriptor instead.
func (*S3StorageMkdirRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{20}
}

func (x *S3StorageMkdirRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3StorageMkdirRequest) GetDirName() string {
	if x != nil {
		return x.DirName
	}
	return ""
}

func (x *S3StorageMkdirRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type S3StorageMkdirReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageMkdirReply) Reset() {
	*x = S3StorageMkdirReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageMkdirReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageMkdirReply) ProtoMessage() {}

func (x *S3StorageMkdirReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageMkdirReply.ProtoReflect.Descriptor instead.
func (*S3StorageMkdirReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{21}
}

func (x *S3StorageMkdirReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageMkdirReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S3StorageMkdirReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type S3StorageDeleteMkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	DirName       string                 `protobuf:"bytes,2,opt,name=dirName,proto3" json:"dirName,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDeleteMkdirRequest) Reset() {
	*x = S3StorageDeleteMkdirRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDeleteMkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDeleteMkdirRequest) ProtoMessage() {}

func (x *S3StorageDeleteMkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDeleteMkdirRequest.ProtoReflect.Descriptor instead.
func (*S3StorageDeleteMkdirRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{22}
}

func (x *S3StorageDeleteMkdirRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3StorageDeleteMkdirRequest) GetDirName() string {
	if x != nil {
		return x.DirName
	}
	return ""
}

func (x *S3StorageDeleteMkdirRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type S3StorageDeleteMkdirReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDeleteMkdirReply) Reset() {
	*x = S3StorageDeleteMkdirReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDeleteMkdirReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDeleteMkdirReply) ProtoMessage() {}

func (x *S3StorageDeleteMkdirReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDeleteMkdirReply.ProtoReflect.Descriptor instead.
func (*S3StorageDeleteMkdirReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{23}
}

func (x *S3StorageDeleteMkdirReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageDeleteMkdirReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type S3StorageUploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	BucketName    string                 `protobuf:"bytes,4,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageUploadFileRequest) Reset() {
	*x = S3StorageUploadFileRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageUploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageUploadFileRequest) ProtoMessage() {}

func (x *S3StorageUploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageUploadFileRequest.ProtoReflect.Descriptor instead.
func (*S3StorageUploadFileRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{24}
}

func (x *S3StorageUploadFileRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *S3StorageUploadFileRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *S3StorageUploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *S3StorageUploadFileRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type S3StorageUploadFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *S3Object              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageUploadFileReply) Reset() {
	*x = S3StorageUploadFileReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageUploadFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageUploadFileReply) ProtoMessage() {}

func (x *S3StorageUploadFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageUploadFileReply.ProtoReflect.Descriptor instead.
func (*S3StorageUploadFileReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{25}
}

func (x *S3StorageUploadFileReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageUploadFileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S3StorageUploadFileReply) GetData() *S3Object {
	if x != nil {
		return x.Data
	}
	return nil
}

type S3StorageDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDownloadRequest) Reset() {
	*x = S3StorageDownloadRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDownloadRequest) ProtoMessage() {}

func (x *S3StorageDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDownloadRequest.ProtoReflect.Descriptor instead.
func (*S3StorageDownloadRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{26}
}

func (x *S3StorageDownloadRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3StorageDownloadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type S3StorageDownloadReply struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *S3StorageDownloadReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDownloadReply) Reset() {
	*x = S3StorageDownloadReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDownloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDownloadReply) ProtoMessage() {}

func (x *S3StorageDownloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDownloadReply.ProtoReflect.Descriptor instead.
func (*S3StorageDownloadReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{27}
}

func (x *S3StorageDownloadReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageDownloadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S3StorageDownloadReply) GetData() *S3StorageDownloadReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type S3StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDeleteRequest) Reset() {
	*x = S3StorageDeleteRequest{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDeleteRequest) ProtoMessage() {}

func (x *S3StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*S3StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{28}
}

func (x *S3StorageDeleteRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3StorageDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type S3StorageDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDeleteReply) Reset() {
	*x = S3StorageDeleteReply{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDeleteReply) ProtoMessage() {}

func (x *S3StorageDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDeleteReply.ProtoReflect.Descriptor instead.
func (*S3StorageDeleteReply) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{29}
}

func (x *S3StorageDeleteReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S3StorageDeleteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBucketReply_BucketVo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	CreatedTime   int64                  `protobuf:"varint,3,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketReply_BucketVo) Reset() {
	*x = ListBucketReply_BucketVo{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketReply_BucketVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketReply_BucketVo) ProtoMessage() {}

func (x *ListBucketReply_BucketVo) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketReply_BucketVo.ProtoReflect.Descriptor instead.
func (*ListBucketReply_BucketVo) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ListBucketReply_BucketVo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListBucketReply_BucketVo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListBucketReply_BucketVo) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type ListBucketReply_Data struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*ListBucketReply_BucketVo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketReply_Data) Reset() {
	*x = ListBucketReply_Data{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketReply_Data) ProtoMessage() {}

func (x *ListBucketReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketReply_Data.ProtoReflect.Descriptor instead.
func (*ListBucketReply_Data) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{16, 1}
}

func (x *ListBucketReply_Data) GetList() []*ListBucketReply_BucketVo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListBucketReply_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBucketReply_Data) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBucketReply_Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type S3StorageInBucketListReply_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*S3Object            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageInBucketListReply_Data) Reset() {
	*x = S3StorageInBucketListReply_Data{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageInBucketListReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageInBucketListReply_Data) ProtoMessage() {}

func (x *S3StorageInBucketListReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageInBucketListReply_Data.ProtoReflect.Descriptor instead.
func (*S3StorageInBucketListReply_Data) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{19, 0}
}

func (x *S3StorageInBucketListReply_Data) GetList() []*S3Object {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *S3StorageInBucketListReply_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *S3StorageInBucketListReply_Data) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *S3StorageInBucketListReply_Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type S3StorageDownloadReply_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3StorageDownloadReply_Data) Reset() {
	*x = S3StorageDownloadReply_Data{}
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageDownloadReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageDownloadReply_Data) ProtoMessage() {}

func (x *S3StorageDownloadReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_server_compute_v1_storage_s3_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageDownloadReply_Data.ProtoReflect.Descriptor instead.
func (*S3StorageDownloadReply_Data) Descriptor() ([]byte, []int) {
	return file_server_compute_v1_storage_s3_proto_rawDescGZIP(), []int{27, 0}
}

func (x *S3StorageDownloadReply_Data) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *S3StorageDownloadReply_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_server_compute_v1_storage_s3_proto protoreflect.FileDescriptor

const file_server_compute_v1_storage_s3_proto_rawDesc = "" +
	"\n" +
	"\"server/compute/v1/storage_s3.proto\x12\x11server.compute.v1\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12CreateS3KeyRequest\"@\n" +
	"\x10CreateS3KeyReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb0\x01\n" +
	"\x06S3User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\taccessKey\x18\x02 \x01(\tR\taccessKey\x12\x1c\n" +
	"\tsecretKey\x18\x03 \x01(\tR\tsecretKey\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\"\x1a\n" +
	"\x18GetUserS3UserListRequest\"u\n" +
	"\x16GetUserS3UserListReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.server.compute.v1.S3UserR\x04data\"\xa2\x01\n" +
	"\x14GetUserS3UserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11countryCallCoding\x18\x02 \x01(\tR\x11countryCallCoding\x12(\n" +
	"\x0ftelephoneNumber\x18\x03 \x01(\tR\x0ftelephoneNumber\x12\"\n" +
	"\fvalidateCode\x18\x04 \x01(\tR\fvalidateCode\"q\n" +
	"\x12GetUserS3UserReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.server.compute.v1.S3UserR\x04data\"\xa5\x01\n" +
	"\x17DeleteUserS3UserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11countryCallCoding\x18\x02 \x01(\tR\x11countryCallCoding\x12(\n" +
	"\x0ftelephoneNumber\x18\x03 \x01(\tR\x0ftelephoneNumber\x12\"\n" +
	"\fvalidateCode\x18\x04 \x01(\tR\fvalidateCode\"E\n" +
	"\x15DeleteUserS3UserReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x13CreateBucketRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\"U\n" +
	"\x11CreateBucketReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"5\n" +
	"\x13DeleteBucketRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\"A\n" +
	"\x11DeleteBucketReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x12EmptyBucketRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\"@\n" +
	"\x10EmptyBucketReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x11ListBucketRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xda\x02\n" +
	"\x0fListBucketReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2'.server.compute.v1.ListBucketReply.DataR\x04data\x1aT\n" +
	"\bBucketVo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12 \n" +
	"\vcreatedTime\x18\x03 \x01(\x03R\vcreatedTime\x1a\x85\x01\n" +
	"\x04Data\x12?\n" +
	"\x04list\x18\x01 \x03(\v2+.server.compute.v1.ListBucketReply.BucketVoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\xa7\x01\n" +
	"\bS3Object\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05s3Url\x18\x04 \x01(\tR\x05s3Url\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\x12\x1f\n" +
	"\vlast_modify\x18\a \x01(\x03R\n" +
	"lastModify\x12\x16\n" +
	"\x06prefix\x18\b \x01(\tR\x06prefix\"\x92\x01\n" +
	"\x1cS3StorageInBucketListRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\"\x89\x02\n" +
	"\x1aS3StorageInBucketListReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x04data\x18\x03 \x01(\v22.server.compute.v1.S3StorageInBucketListReply.DataR\x04data\x1au\n" +
	"\x04Data\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.server.compute.v1.S3ObjectR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"i\n" +
	"\x15S3StorageMkdirRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x18\n" +
	"\adirName\x18\x02 \x01(\tR\adirName\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"W\n" +
	"\x13S3StorageMkdirReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"o\n" +
	"\x1bS3StorageDeleteMkdirRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x18\n" +
	"\adirName\x18\x02 \x01(\tR\adirName\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"I\n" +
	"\x19S3StorageDeleteMkdirReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x1aS3StorageUploadFileRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x04 \x01(\tR\n" +
	"bucketName\"y\n" +
	"\x18S3StorageUploadFileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.server.compute.v1.S3ObjectR\x04data\"L\n" +
	"\x18S3StorageDownloadRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xba\x01\n" +
	"\x16S3StorageDownloadReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x01(\v2..server.compute.v1.S3StorageDownloadReply.DataR\x04data\x1a.\n" +
	"\x04Data\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"\x16S3StorageDeleteRequest\x12\x1e\n" +
	"\n" +
	"bucketName\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"D\n" +
	"\x14S3StorageDeleteReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x0f\n" +
	"\tStorageS3\x12{\n" +
	"\vCreateS3Key\x12%.server.compute.v1.CreateS3KeyRequest\x1a#.server.compute.v1.CreateS3KeyReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/s3user/create/key\x12\x7f\n" +
	"\x11GetUserS3UserList\x12+.server.compute.v1.GetUserS3UserListRequest\x1a).server.compute.v1.GetUserS3UserListReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/s3user\x12x\n" +
	"\rGetUserS3User\x12'.server.compute.v1.GetUserS3UserRequest\x1a%.server.compute.v1.GetUserS3UserReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/s3user/{id}\x12\x81\x01\n" +
	"\x10DeleteUserS3User\x12*.server.compute.v1.DeleteUserS3UserRequest\x1a(.server.compute.v1.DeleteUserS3UserReply\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/s3user/{id}\x12u\n" +
	"\fCreateBucket\x12&.server.compute.v1.CreateBucketRequest\x1a$.server.compute.v1.CreateBucketReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/s3bucket\x12\x7f\n" +
	"\fDeleteBucket\x12&.server.compute.v1.DeleteBucketRequest\x1a$.server.compute.v1.DeleteBucketReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/s3bucket/{bucketName}\x12\x82\x01\n" +
	"\vEmptyBucket\x12%.server.compute.v1.EmptyBucketRequest\x1a#.server.compute.v1.EmptyBucketReply\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/s3bucket/{bucketName}/empty\x12l\n" +
	"\n" +
	"ListBucket\x12$.server.compute.v1.ListBucketRequest\x1a\".server.compute.v1.ListBucketReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/s3bucket\x12\xa2\x01\n" +
	"\x15S3StorageInBucketList\x12/.server.compute.v1.S3StorageInBucketListRequest\x1a-.server.compute.v1.S3StorageInBucketListReply\")\x82\xd3\xe4\x93\x02#\x12!/v1/s3bucket/{bucketName}/objects\x12\xac\x01\n" +
	"\x13S3StorageUploadFile\x12-.server.compute.v1.S3StorageUploadFileRequest\x1a+.server.compute.v1.S3StorageUploadFileReply\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/storage/{bucketName}/objects/upload/ersatz\x12\x8d\x01\n" +
	"\x0eS3StorageMkdir\x12(.server.compute.v1.S3StorageMkdirRequest\x1a&.server.compute.v1.S3StorageMkdirReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/storage/{bucketName}/mkdir\x12\x9c\x01\n" +
	"\x14S3StorageDeleteMkdir\x12..server.compute.v1.S3StorageDeleteMkdirRequest\x1a,.server.compute.v1.S3StorageDeleteMkdirReply\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/storage/{bucketName}/mkdir\x12\xa5\x01\n" +
	"\x11S3StorageDownload\x12+.server.compute.v1.S3StorageDownloadRequest\x1a).server.compute.v1.S3StorageDownloadReply\"8\x82\xd3\xe4\x93\x022\x120/v1/storage/{bucketName}/objects/download/ersatz\x12\x96\x01\n" +
	"\x0fS3StorageDelete\x12).server.compute.v1.S3StorageDeleteRequest\x1a'.server.compute.v1.S3StorageDeleteReply\"/\x82\xd3\xe4\x93\x02)*'/v1/storage/{bucketName}/objects/deleteBc\n" +
	"\x0eapi.compute.v1P\x01ZOgithub.com/tntlinking-computeshare/computeshare-server/api/server/compute/v1;v1b\x06proto3"

var (
	file_server_compute_v1_storage_s3_proto_rawDescOnce sync.Once
	file_server_compute_v1_storage_s3_proto_rawDescData []byte
)

func file_server_compute_v1_storage_s3_proto_rawDescGZIP() []byte {
	file_server_compute_v1_storage_s3_proto_rawDescOnce.Do(func() {
		file_server_compute_v1_storage_s3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_compute_v1_storage_s3_proto_rawDesc), len(file_server_compute_v1_storage_s3_proto_rawDesc)))
	})
	return file_server_compute_v1_storage_s3_proto_rawDescData
}

var file_server_compute_v1_storage_s3_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_server_compute_v1_storage_s3_proto_goTypes = []any{
	(*CreateS3KeyRequest)(nil),              // 0: server.compute.v1.CreateS3KeyRequest
	(*CreateS3KeyReply)(nil),                // 1: server.compute.v1.CreateS3KeyReply
	(*S3User)(nil),                          // 2: server.compute.v1.S3User
	(*GetUserS3UserListRequest)(nil),        // 3: server.compute.v1.GetUserS3UserListRequest
	(*GetUserS3UserListReply)(nil),          // 4: server.compute.v1.GetUserS3UserListReply
	(*GetUserS3UserRequest)(nil),            // 5: server.compute.v1.GetUserS3UserRequest
	(*GetUserS3UserReply)(nil),              // 6: server.compute.v1.GetUserS3UserReply
	(*DeleteUserS3UserRequest)(nil),         // 7: server.compute.v1.DeleteUserS3UserRequest
	(*DeleteUserS3UserReply)(nil),           // 8: server.compute.v1.DeleteUserS3UserReply
	(*CreateBucketRequest)(nil),             // 9: server.compute.v1.CreateBucketRequest
	(*CreateBucketReply)(nil),               // 10: server.compute.v1.CreateBucketReply
	(*DeleteBucketRequest)(nil),             // 11: server.compute.v1.DeleteBucketRequest
	(*DeleteBucketReply)(nil),               // 12: server.compute.v1.DeleteBucketReply
	(*EmptyBucketRequest)(nil),              // 13: server.compute.v1.EmptyBucketRequest
	(*EmptyBucketReply)(nil),                // 14: server.compute.v1.EmptyBucketReply
	(*ListBucketRequest)(nil),               // 15: server.compute.v1.ListBucketRequest
	(*ListBucketReply)(nil),                 // 16: server.compute.v1.ListBucketReply
	(*S3Object)(nil),                        // 17: server.compute.v1.S3Object
	(*S3StorageInBucketListRequest)(nil),    // 18: server.compute.v1.S3StorageInBucketListRequest
	(*S3StorageInBucketListReply)(nil),      // 19: server.compute.v1.S3StorageInBucketListReply
	(*S3StorageMkdirRequest)(nil),           // 20: server.compute.v1.S3StorageMkdirRequest
	(*S3StorageMkdirReply)(nil),             // 21: server.compute.v1.S3StorageMkdirReply
	(*S3StorageDeleteMkdirRequest)(nil),     // 22: server.compute.v1.S3StorageDeleteMkdirRequest
	(*S3StorageDeleteMkdirReply)(nil),       // 23: server.compute.v1.S3StorageDeleteMkdirReply
	(*S3StorageUploadFileRequest)(nil),      // 24: server.compute.v1.S3StorageUploadFileRequest
	(*S3StorageUploadFileReply)(nil),        // 25: server.compute.v1.S3StorageUploadFileReply
	(*S3StorageDownloadRequest)(nil),        // 26: server.compute.v1.S3StorageDownloadRequest
	(*S3StorageDownloadReply)(nil),          // 27: server.compute.v1.S3StorageDownloadReply
	(*S3StorageDeleteRequest)(nil),          // 28: server.compute.v1.S3StorageDeleteRequest
	(*S3StorageDeleteReply)(nil),            // 29: server.compute.v1.S3StorageDeleteReply
	(*ListBucketReply_BucketVo)(nil),        // 30: server.compute.v1.ListBucketReply.BucketVo
	(*ListBucketReply_Data)(nil),            // 31: server.compute.v1.ListBucketReply.Data
	(*S3StorageInBucketListReply_Data)(nil), // 32: server.compute.v1.S3StorageInBucketListReply.Data
	(*S3StorageDownloadReply_Data)(nil),     // 33: server.compute.v1.S3StorageDownloadReply.Data
}
var file_server_compute_v1_storage_s3_proto_depIdxs = []int32{
	2,  // 0: server.compute.v1.GetUserS3UserListReply.data:type_name -> server.compute.v1.S3User
	2,  // 1: server.compute.v1.GetUserS3UserReply.data:type_name -> server.compute.v1.S3User
	31, // 2: server.compute.v1.ListBucketReply.data:type_name -> server.compute.v1.ListBucketReply.Data
	32, // 3: server.compute.v1.S3StorageInBucketListReply.data:type_name -> server.compute.v1.S3StorageInBucketListReply.Data
	17, // 4: server.compute.v1.S3StorageUploadFileReply.data:type_name -> server.compute.v1.S3Object
	33, // 5: server.compute.v1.S3StorageDownloadReply.data:type_name -> server.compute.v1.S3StorageDownloadReply.Data
	30, // 6: server.compute.v1.ListBucketReply.Data.list:type_name -> server.compute.v1.ListBucketReply.BucketVo
	17, // 7: server.compute.v1.S3StorageInBucketListReply.Data.list:type_name -> server.compute.v1.S3Object
	0,  // 8: server.compute.v1.StorageS3.CreateS3Key:input_type -> server.compute.v1.CreateS3KeyRequest
	3,  // 9: server.compute.v1.StorageS3.GetUserS3UserList:input_type -> server.compute.v1.GetUserS3UserListRequest
	5,  // 10: server.compute.v1.StorageS3.GetUserS3User:input_type -> server.compute.v1.GetUserS3UserRequest
	7,  // 11: server.compute.v1.StorageS3.DeleteUserS3User:input_type -> server.compute.v1.DeleteUserS3UserRequest
	9,  // 12: server.compute.v1.StorageS3.CreateBucket:input_type -> server.compute.v1.CreateBucketRequest
	11, // 13: server.compute.v1.StorageS3.DeleteBucket:input_type -> server.compute.v1.DeleteBucketRequest
	13, // 14: server.compute.v1.StorageS3.EmptyBucket:input_type -> server.compute.v1.EmptyBucketRequest
	15, // 15: server.compute.v1.StorageS3.ListBucket:input_type -> server.compute.v1.ListBucketRequest
	18, // 16: server.compute.v1.StorageS3.S3StorageInBucketList:input_type -> server.compute.v1.S3StorageInBucketListRequest
	24, // 17: server.compute.v1.StorageS3.S3StorageUploadFile:input_type -> server.compute.v1.S3StorageUploadFileRequest
	20, // 18: server.compute.v1.StorageS3.S3StorageMkdir:input_type -> server.compute.v1.S3StorageMkdirRequest
	22, // 19: server.compute.v1.StorageS3.S3StorageDeleteMkdir:input_type -> server.compute.v1.S3StorageDeleteMkdirRequest
	26, // 20: server.compute.v1.StorageS3.S3StorageDownload:input_type -> server.compute.v1.S3StorageDownloadRequest
	28, // 21: server.compute.v1.StorageS3.S3StorageDelete:input_type -> server.compute.v1.S3StorageDeleteRequest
	1,  // 22: server.compute.v1.StorageS3.CreateS3Key:output_type -> server.compute.v1.CreateS3KeyReply
	4,  // 23: server.compute.v1.StorageS3.GetUserS3UserList:output_type -> server.compute.v1.GetUserS3UserListReply
	6,  // 24: server.compute.v1.StorageS3.GetUserS3User:output_type -> server.compute.v1.GetUserS3UserReply
	8,  // 25: server.compute.v1.StorageS3.DeleteUserS3User:output_type -> server.compute.v1.DeleteUserS3UserReply
	10, // 26: server.compute.v1.StorageS3.CreateBucket:output_type -> server.compute.v1.CreateBucketReply
	12, // 27: server.compute.v1.StorageS3.DeleteBucket:output_type -> server.compute.v1.DeleteBucketReply
	14, // 28: server.compute.v1.StorageS3.EmptyBucket:output_type -> server.compute.v1.EmptyBucketReply
	16, // 29: server.compute.v1.StorageS3.ListBucket:output_type -> server.compute.v1.ListBucketReply
	19, // 30: server.compute.v1.StorageS3.S3StorageInBucketList:output_type -> server.compute.v1.S3StorageInBucketListReply
	25, // 31: server.compute.v1.StorageS3.S3StorageUploadFile:output_type -> server.compute.v1.S3StorageUploadFileReply
	21, // 32: server.compute.v1.StorageS3.S3StorageMkdir:output_type -> server.compute.v1.S3StorageMkdirReply
	23, // 33: server.compute.v1.StorageS3.S3StorageDeleteMkdir:output_type -> server.compute.v1.S3StorageDeleteMkdirReply
	27, // 34: server.compute.v1.StorageS3.S3StorageDownload:output_type -> server.compute.v1.S3StorageDownloadReply
	29, // 35: server.compute.v1.StorageS3.S3StorageDelete:output_type -> server.compute.v1.S3StorageDeleteReply
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_compute_v1_storage_s3_proto_init() }
func file_server_compute_v1_storage_s3_proto_init() {
	if File_server_compute_v1_storage_s3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_compute_v1_storage_s3_proto_rawDesc), len(file_server_compute_v1_storage_s3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_compute_v1_storage_s3_proto_goTypes,
		DependencyIndexes: file_server_compute_v1_storage_s3_proto_depIdxs,
		MessageInfos:      file_server_compute_v1_storage_s3_proto_msgTypes,
	}.Build()
	File_server_compute_v1_storage_s3_proto = out.File
	file_server_compute_v1_storage_s3_proto_goTypes = nil
	file_server_compute_v1_storage_s3_proto_depIdxs = nil
}
