### POST
POST http://127.0.0.1:8000/v1/storage/upload
Authorization: Bearer {{ access_token }}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="some.pdf"
Content-Type: application/json

< /tmp/some.pdf
--WebAppBoundary--


### 下载
POST https://computeshare-frontend.hamster.newtouch.com/api/v1/storage/download?id=5c82490f-7479-4394-adcc-d69b00a80282
Authorization: Bearer {{ access_token }}


###

# curl -X 'DELETE'
#  'HTTP://127.0.0.1:8000/v1/user/a3546e51-8976-44ea-94a3-1c74ebda0118'
#  -H 'accept: application/json'
GET  http://127.0.0.1:8000/v1/user
accept: application/json
Authorization: Bearer {{ access_token }}

###

### POST /v1/compute-power/upload
POST http://127.0.0.1:8000/v1/compute-power/upload
x-md-globa-owner: mo
owner: mo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data;
Content-Type: text/plain

73640b0d-ce18-45c1-beff-e06faa4a05f9
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="substrate学习文档.md"
Content-Type: application/json

< /Users/abing/Desktop/substrate学习文档.md
--WebAppBoundary--


###
###
GET http://127.0.0.1:8000/v1/compute-power/script/info/1
accept: application/json
Authorization: Bearer {{ access_token }}


###
GET http://127.0.0.1:8000/v1/user
accept: application/json
Authorization: Bearer {{ access_token }}


### 修改密码
PUT http://127.0.0.1:8000/v1/user/password
Content-Type: application/json
accept: application/json
Authorization: Bearer {{ access_token }}

{
  "oldPassword": "",
  "newPassword": "Abcd1234"
}

### 验证码
#POST http://computeshare.hamster.newtouch.com/v1/sms/send
POST  http://127.0.0.1:8000/v1/sms/send
Content-Type: application/json

{
  "countryCallCoding": "+86",
  "telephoneNumber": "15001747213"
}


### 登录
POST http://computeshare.hamster.newtouch.com/v1/user/login_by_vc
Content-Type: application/json

{
  "countryCallCoding": "+86",
  "telephoneNumber": "15001747213",
  "validateCode": "000000"
}


### 创建虚拟机
POST  http://127.0.0.1:8000/v1/instance
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "specId": 1,
  "imageId": 1,
  "duration": 1,
  "name": "my-vm",
  "publicKey":  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2mLWYddGeahdk6i3muy72XDbppnG4LIDhyj/rSuzLstdVLI7mF7efkwCZgyYcYRJoIjNI5mnb17o7/qVWdgGSiMnSgiPcw4r0Dp1pghWXBEog3o7pI3gicY6//Y4+liqypBEDmBSJnDsMJqVARzFV0rjJLhYSCbYk99LPB1ZLj0mDvIY/1SjRR9bfPuW9Ht6QjkS9DEWIdTrJ0dAaGwJkc+a5pCVzcopq4ycvBVLEnEq4xCrhbNx/LrpYxytA7WXg6kUcN+4Me63QVPxUExcn14qXr5uYxo+ePkoBCNdbqFsm0Z1rxrEX8oGDHvAfsoCpQr/OV8J5WwO7i/QIOyK7 mohaijiang110@163.com",
  "password":  "Abcd12345"
}

### 关闭虚拟机
PUT  http://127.0.0.1:8000/v1/instance/{{instanceId}}/stop
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{

}

### 启动虚拟机
PUT  http://127.0.0.1:8000/v1/instance/{{instanceId}}/start
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 删除虚拟机
DELETE  http://127.0.0.1:8000/v1/instance/{{instanceId}}
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 查询虚拟机
GET  http://127.0.0.1:8000/v1/instance
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 查询文件列表
GET  https://computeshare.hamster.newtouch.com/v1/storage
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 创建网络映射
POST  http://127.0.0.1:8000/v1/network-mappings
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "name": "ssh2-port",
  "computer_id": "a5992431-dc1c-49b7-a537-f9e40b2355b6",
  "computer_port": 22
}

### 查询网络映射
GET  http://127.0.0.1:8000/v1/network-mappings/page?computer_id=00d460f0-ec1a-4a0f-a452-1afb4b5d1686&page=1&size=1
Content-Type: application/json
Authorization: Bearer {{ access_token }}

### 网络映射详情
GET  http://127.0.0.1:8000/v1/network-mappings/7f4d03d5-445e-4b1b-9a3c-227123a0f9c6
Content-Type: application/json
Authorization: Bearer {{ access_token }}

### 删除网络映射
DELETE   http://127.0.0.1:8000/v1/network-mappings/62470099-64a0-40e3-9469-c2ecbc7b35ce
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 查询任务
GET  http://127.0.0.1:8000/v1/queue/task?id=00c460f0-ec1a-4a0f-a452-1afb4b5d1686
Content-Type: application/json
Authorization: Bearer {{ access_token }}

### 更新任务状态
PUT  http://127.0.0.1:8000/v1/queue/task
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "id":"ac4d35fc-7ec1-4275-bf48-5fcc568736cd",
  "agentId":"00c460f0-ec1a-4a0f-a452-1afb4b5d1686",
  "status":1
}

### 获取VNC CONSOLE
GET http://127.0.0.1:8000/v1/instance/{{ instanceId }}/console
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 查询网络映射
GET https://computeshare.hamster.newtouch.com/v1/network-mappings/page?page=1&size=10
#GET http://127.0.0.1:8000/v1/network-mappings/page?page=1&size=10
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 新增网络映射
POST https://computeshare.hamster.newtouch.com/v1/network-mappings
#POST http://127.0.0.1:8000/v1/network-mappings
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "name": "some-ssh",
  "computerId": "{{ instanceId }}",
  "computerPort": 22
}


### 新增域名绑定
#POST http://127.0.0.1:8000/v1/domain-binding
POST https://computeshare.hamster.newtouch.com/v1/domain-binding
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "networkMappingId": "05f536a9-2064-416d-a561-3bc9d0deeffc",
  "name": "d2",
  "domain": "test1.computeshare.hamster.newtouch.com"
}


### 新增网络提供
POST http://127.0.0.1:8000/v1/storage_provider
Content-Type: application/json
Authorization: Bearer {{ access_token }}

{
  "agentId": "5b0c430e-3f65-461b-8593-6ecad56460bd"
}

### 下一个网络端口
GET https://computeshare.hamster.newtouch.com/v1/network-mappings/next?computerId=2f5e4fdc-b976-4870-9307-ac7705ae32e0
Content-Type: application/json
Authorization: Bearer {{ access_token }}


### 域名检查
GET https://computeshare.hamster.newtouch.com/v1/domain-binding/nslookup?domain=test2.computeshare.newtouch.com&networkMappingId=2fe434fc-7e7d-4abb-9b0f-d1870b0625e6
#GET http://127.0.0.1:8000/v1/domain-binding/nslookup?domain=test2.computeshare.newtouch.com&networkMappingId=2fe434fc-7e7d-4abb-9b0f-d1870b0625e6
Content-Type: application/json
Authorization: Bearer {{ access_token }}
