### POST
POST http://127.0.0.1:8000/v1/storage/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhZDkwMWZlZi0xZTBjLTQxMmQtODE0My0xNzExMTA0ZmMxZGYiLCJleHAiOjE2OTU0MzY3NjZ9.UE51p2kQVDEtM-VNfsFe2S0-TSzVox2K1EVjV9G-LOg
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="parentId"
Content-Type: text/plain

73640b0d-ce18-45c1-beff-e06faa4a05f9
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="abc.txt"
Content-Type: application/json

< /tmp/abc.txt
--WebAppBoundary--


### 下载
POST http://127.0.0.1:8000/v1/storage/download?id=386f199e-1704-4a40-bd8c-10f2969a9e54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhZDkwMWZlZi0xZTBjLTQxMmQtODE0My0xNzExMTA0ZmMxZGYiLCJleHAiOjE2OTU0MzY3NjZ9.UE51p2kQVDEtM-VNfsFe2S0-TSzVox2K1EVjV9G-LOg

###

# curl -X 'DELETE'
#  'HTTP://127.0.0.1:8000/v1/user/a3546e51-8976-44ea-94a3-1c74ebda0118'
#  -H 'accept: application/json'
GET  http://127.0.0.1:8000/v1/user
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJkMmIyYzE1Yy1hM2RmLTQ1OGItYmVjMC1jNTU2YWYxNDMxOTMiLCJleHAiOjE2OTUyNzY5ODR9.GU4Va3rQSzT2YKsZUxJIJQdf4TpwCdIANVyJkdjKoPY

###

### POST /v1/compute-power/upload
POST http://127.0.0.1:8000/v1/compute-power/upload
x-md-globa-owner: mo
owner: mo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data;
Content-Type: text/plain

73640b0d-ce18-45c1-beff-e06faa4a05f9
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="substrate学习文档.md"
Content-Type: application/json

< /Users/abing/Desktop/substrate学习文档.md
--WebAppBoundary--


###
###
GET http://127.0.0.1:8000/v1/compute-power/script/info/1
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6ImEzNTQ2ZTUxLTg5NzYtNDRlYS05NGEzLTFjNzRlYmRhMDExOCIsImV4cCI6MTY5NDU3NjY1N30.PMUmQZcv0u71X4XKQ6lqLx2ok_kUmL3Ydf_lX1fZblI




###
GET http://127.0.0.1:8000/v1/user
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNzU1OWRlZi1jNTE0LTQxZmQtYjA0NC1iNTliODFmMmZiNmIiLCJleHAiOjE2OTUyODMxMjF9.gh8uLnrTGERkN8k-bkiAYvMyqs1O8vrNJIeMCoPsSO4


### 修改密码
PUT http://127.0.0.1:8000/v1/user/password
Content-Type: application/json
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNzU1OWRlZi1jNTE0LTQxZmQtYjA0NC1iNTliODFmMmZiNmIiLCJleHAiOjE2OTUyODMxMjF9.gh8uLnrTGERkN8k-bkiAYvMyqs1O8vrNJIeMCoPsSO4

{
  "oldPassword": "",
  "newPassword": "Abcd1234"
}

### 验证码
POST http://127.0.0.1:8000/v1/sms/send
#POST  http://127.0.0.1:8000/v1/sms/send
Content-Type: application/json

{
  "countryCallCoding": "+86",
  "telephoneNumber": "15001747213"
}


### 登录
POST http://127.0.0.1:8000/v1/user/login_by_vc
Content-Type: application/json

{
  "countryCallCoding": "+86",
  "telephoneNumber": "15001747213",
  "validateCode": "000000"
}


### 创建虚拟机
POST  http://127.0.0.1:8000/v1/instance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNzU1OWRlZi1jNTE0LTQxZmQtYjA0NC1iNTliODFmMmZiNmIiLCJleHAiOjE2OTU2OTg3Nzl9.PTmJQ29qS2RcB6eegLzw7epSseW1s84LzEA87JR9xsY

{
  "specId": 1,
  "imageId": 1,
  "duration": 1,
  "name": "my-vm"
}

### 关闭虚拟机
PUT  http://127.0.0.1:8000/v1/instance/1e6d989f-1dac-414e-a914-c93c0d23d64d/stop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhZDkwMWZlZi0xZTBjLTQxMmQtODE0My0xNzExMTA0ZmMxZGYiLCJleHAiOjE2OTU0MzY3NjZ9.UE51p2kQVDEtM-VNfsFe2S0-TSzVox2K1EVjV9G-LOg

{

}

### 启动虚拟机
PUT  http://127.0.0.1:8000/v1/instance/1e6d989f-1dac-414e-a914-c93c0d23d64d/start
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhZDkwMWZlZi0xZTBjLTQxMmQtODE0My0xNzExMTA0ZmMxZGYiLCJleHAiOjE2OTU0MzY3NjZ9.UE51p2kQVDEtM-VNfsFe2S0-TSzVox2K1EVjV9G-LOg


### 删除虚拟机
DELETE  http://127.0.0.1:8000/v1/instance/59029fbc-54ee-4e51-b86b-570edafc4fc7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhZDkwMWZlZi0xZTBjLTQxMmQtODE0My0xNzExMTA0ZmMxZGYiLCJleHAiOjE2OTU0MzY3NjZ9.UE51p2kQVDEtM-VNfsFe2S0-TSzVox2K1EVjV9G-LOg


### 查询虚拟机
GET  http://127.0.0.1:8000/v1/instance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNzU1OWRlZi1jNTE0LTQxZmQtYjA0NC1iNTliODFmMmZiNmIiLCJleHAiOjE2OTU2OTg3Nzl9.PTmJQ29qS2RcB6eegLzw7epSseW1s84LzEA87JR9xsY


### 查询文件列表
GET  https://computeshare.hamster.newtouch.com/v1/storage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNzU1OWRlZi1jNTE0LTQxZmQtYjA0NC1iNTliODFmMmZiNmIiLCJleHAiOjE2OTU2OTg3Nzl9.PTmJQ29qS2RcB6eegLzw7epSseW1s84LzEA87JR9xsY
