// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tntlinking-computeshare/computeshare-server/internal/data/ent/computespec"
	"github.com/tntlinking-computeshare/computeshare-server/internal/data/ent/predicate"
)

// ComputeSpecDelete is the builder for deleting a ComputeSpec entity.
type ComputeSpecDelete struct {
	config
	hooks    []Hook
	mutation *ComputeSpecMutation
}

// Where appends a list predicates to the ComputeSpecDelete builder.
func (_d *ComputeSpecDelete) Where(ps ...predicate.ComputeSpec) *ComputeSpecDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ComputeSpecDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ComputeSpecDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ComputeSpecDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(computespec.Table, sqlgraph.NewFieldSpec(computespec.FieldID, field.TypeInt32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ComputeSpecDeleteOne is the builder for deleting a single ComputeSpec entity.
type ComputeSpecDeleteOne struct {
	_d *ComputeSpecDelete
}

// Where appends a list predicates to the ComputeSpecDelete builder.
func (_d *ComputeSpecDeleteOne) Where(ps ...predicate.ComputeSpec) *ComputeSpecDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ComputeSpecDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{computespec.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ComputeSpecDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
