// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mohaijiang/computeshare-server/internal/data/ent/computespecprice"
)

// ComputeSpecPriceCreate is the builder for creating a ComputeSpecPrice entity.
type ComputeSpecPriceCreate struct {
	config
	mutation *ComputeSpecPriceMutation
	hooks    []Hook
}

// SetFkComputeSpecID sets the "fk_compute_spec_id" field.
func (_c *ComputeSpecPriceCreate) SetFkComputeSpecID(v int32) *ComputeSpecPriceCreate {
	_c.mutation.SetFkComputeSpecID(v)
	return _c
}

// SetDay sets the "day" field.
func (_c *ComputeSpecPriceCreate) SetDay(v int32) *ComputeSpecPriceCreate {
	_c.mutation.SetDay(v)
	return _c
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_c *ComputeSpecPriceCreate) SetNillableDay(v *int32) *ComputeSpecPriceCreate {
	if v != nil {
		_c.SetDay(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ComputeSpecPriceCreate) SetPrice(v float32) *ComputeSpecPriceCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *ComputeSpecPriceCreate) SetNillablePrice(v *float32) *ComputeSpecPriceCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ComputeSpecPriceCreate) SetID(v int32) *ComputeSpecPriceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ComputeSpecPriceMutation object of the builder.
func (_c *ComputeSpecPriceCreate) Mutation() *ComputeSpecPriceMutation {
	return _c.mutation
}

// Save creates the ComputeSpecPrice in the database.
func (_c *ComputeSpecPriceCreate) Save(ctx context.Context) (*ComputeSpecPrice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ComputeSpecPriceCreate) SaveX(ctx context.Context) *ComputeSpecPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComputeSpecPriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComputeSpecPriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ComputeSpecPriceCreate) defaults() {
	if _, ok := _c.mutation.Day(); !ok {
		v := computespecprice.DefaultDay
		_c.mutation.SetDay(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := computespecprice.DefaultPrice
		_c.mutation.SetPrice(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ComputeSpecPriceCreate) check() error {
	if _, ok := _c.mutation.FkComputeSpecID(); !ok {
		return &ValidationError{Name: "fk_compute_spec_id", err: errors.New(`ent: missing required field "ComputeSpecPrice.fk_compute_spec_id"`)}
	}
	if _, ok := _c.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "ComputeSpecPrice.day"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ComputeSpecPrice.price"`)}
	}
	return nil
}

func (_c *ComputeSpecPriceCreate) sqlSave(ctx context.Context) (*ComputeSpecPrice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ComputeSpecPriceCreate) createSpec() (*ComputeSpecPrice, *sqlgraph.CreateSpec) {
	var (
		_node = &ComputeSpecPrice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(computespecprice.Table, sqlgraph.NewFieldSpec(computespecprice.FieldID, field.TypeInt32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.FkComputeSpecID(); ok {
		_spec.SetField(computespecprice.FieldFkComputeSpecID, field.TypeInt32, value)
		_node.FkComputeSpecID = value
	}
	if value, ok := _c.mutation.Day(); ok {
		_spec.SetField(computespecprice.FieldDay, field.TypeInt32, value)
		_node.Day = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(computespecprice.FieldPrice, field.TypeFloat32, value)
		_node.Price = value
	}
	return _node, _spec
}

// ComputeSpecPriceCreateBulk is the builder for creating many ComputeSpecPrice entities in bulk.
type ComputeSpecPriceCreateBulk struct {
	config
	err      error
	builders []*ComputeSpecPriceCreate
}

// Save creates the ComputeSpecPrice entities in the database.
func (_c *ComputeSpecPriceCreateBulk) Save(ctx context.Context) ([]*ComputeSpecPrice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ComputeSpecPrice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComputeSpecPriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ComputeSpecPriceCreateBulk) SaveX(ctx context.Context) []*ComputeSpecPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComputeSpecPriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComputeSpecPriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
