// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mohaijiang/computeshare-server/internal/data/ent/predicate"
	"github.com/mohaijiang/computeshare-server/internal/data/ent/script"
	"github.com/mohaijiang/computeshare-server/internal/data/ent/scriptexecutionrecord"
)

// ScriptExecutionRecordQuery is the builder for querying ScriptExecutionRecord entities.
type ScriptExecutionRecordQuery struct {
	config
	ctx        *QueryContext
	order      []scriptexecutionrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.ScriptExecutionRecord
	withScript *ScriptQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScriptExecutionRecordQuery builder.
func (serq *ScriptExecutionRecordQuery) Where(ps ...predicate.ScriptExecutionRecord) *ScriptExecutionRecordQuery {
	serq.predicates = append(serq.predicates, ps...)
	return serq
}

// Limit the number of records to be returned by this query.
func (serq *ScriptExecutionRecordQuery) Limit(limit int) *ScriptExecutionRecordQuery {
	serq.ctx.Limit = &limit
	return serq
}

// Offset to start from.
func (serq *ScriptExecutionRecordQuery) Offset(offset int) *ScriptExecutionRecordQuery {
	serq.ctx.Offset = &offset
	return serq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (serq *ScriptExecutionRecordQuery) Unique(unique bool) *ScriptExecutionRecordQuery {
	serq.ctx.Unique = &unique
	return serq
}

// Order specifies how the records should be ordered.
func (serq *ScriptExecutionRecordQuery) Order(o ...scriptexecutionrecord.OrderOption) *ScriptExecutionRecordQuery {
	serq.order = append(serq.order, o...)
	return serq
}

// QueryScript chains the current query on the "script" edge.
func (serq *ScriptExecutionRecordQuery) QueryScript() *ScriptQuery {
	query := (&ScriptClient{config: serq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := serq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := serq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scriptexecutionrecord.Table, scriptexecutionrecord.FieldID, selector),
			sqlgraph.To(script.Table, script.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scriptexecutionrecord.ScriptTable, scriptexecutionrecord.ScriptColumn),
		)
		fromU = sqlgraph.SetNeighbors(serq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScriptExecutionRecord entity from the query.
// Returns a *NotFoundError when no ScriptExecutionRecord was found.
func (serq *ScriptExecutionRecordQuery) First(ctx context.Context) (*ScriptExecutionRecord, error) {
	nodes, err := serq.Limit(1).All(setContextOp(ctx, serq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scriptexecutionrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) FirstX(ctx context.Context) *ScriptExecutionRecord {
	node, err := serq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScriptExecutionRecord ID from the query.
// Returns a *NotFoundError when no ScriptExecutionRecord ID was found.
func (serq *ScriptExecutionRecordQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = serq.Limit(1).IDs(setContextOp(ctx, serq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scriptexecutionrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) FirstIDX(ctx context.Context) int32 {
	id, err := serq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScriptExecutionRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScriptExecutionRecord entity is found.
// Returns a *NotFoundError when no ScriptExecutionRecord entities are found.
func (serq *ScriptExecutionRecordQuery) Only(ctx context.Context) (*ScriptExecutionRecord, error) {
	nodes, err := serq.Limit(2).All(setContextOp(ctx, serq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scriptexecutionrecord.Label}
	default:
		return nil, &NotSingularError{scriptexecutionrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) OnlyX(ctx context.Context) *ScriptExecutionRecord {
	node, err := serq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScriptExecutionRecord ID in the query.
// Returns a *NotSingularError when more than one ScriptExecutionRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (serq *ScriptExecutionRecordQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = serq.Limit(2).IDs(setContextOp(ctx, serq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scriptexecutionrecord.Label}
	default:
		err = &NotSingularError{scriptexecutionrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := serq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScriptExecutionRecords.
func (serq *ScriptExecutionRecordQuery) All(ctx context.Context) ([]*ScriptExecutionRecord, error) {
	ctx = setContextOp(ctx, serq.ctx, "All")
	if err := serq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScriptExecutionRecord, *ScriptExecutionRecordQuery]()
	return withInterceptors[[]*ScriptExecutionRecord](ctx, serq, qr, serq.inters)
}

// AllX is like All, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) AllX(ctx context.Context) []*ScriptExecutionRecord {
	nodes, err := serq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScriptExecutionRecord IDs.
func (serq *ScriptExecutionRecordQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if serq.ctx.Unique == nil && serq.path != nil {
		serq.Unique(true)
	}
	ctx = setContextOp(ctx, serq.ctx, "IDs")
	if err = serq.Select(scriptexecutionrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) IDsX(ctx context.Context) []int32 {
	ids, err := serq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (serq *ScriptExecutionRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, serq.ctx, "Count")
	if err := serq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, serq, querierCount[*ScriptExecutionRecordQuery](), serq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) CountX(ctx context.Context) int {
	count, err := serq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (serq *ScriptExecutionRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, serq.ctx, "Exist")
	switch _, err := serq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (serq *ScriptExecutionRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := serq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScriptExecutionRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (serq *ScriptExecutionRecordQuery) Clone() *ScriptExecutionRecordQuery {
	if serq == nil {
		return nil
	}
	return &ScriptExecutionRecordQuery{
		config:     serq.config,
		ctx:        serq.ctx.Clone(),
		order:      append([]scriptexecutionrecord.OrderOption{}, serq.order...),
		inters:     append([]Interceptor{}, serq.inters...),
		predicates: append([]predicate.ScriptExecutionRecord{}, serq.predicates...),
		withScript: serq.withScript.Clone(),
		// clone intermediate query.
		sql:  serq.sql.Clone(),
		path: serq.path,
	}
}

// WithScript tells the query-builder to eager-load the nodes that are connected to
// the "script" edge. The optional arguments are used to configure the query builder of the edge.
func (serq *ScriptExecutionRecordQuery) WithScript(opts ...func(*ScriptQuery)) *ScriptExecutionRecordQuery {
	query := (&ScriptClient{config: serq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	serq.withScript = query
	return serq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScriptExecutionRecord.Query().
//		GroupBy(scriptexecutionrecord.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (serq *ScriptExecutionRecordQuery) GroupBy(field string, fields ...string) *ScriptExecutionRecordGroupBy {
	serq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScriptExecutionRecordGroupBy{build: serq}
	grbuild.flds = &serq.ctx.Fields
	grbuild.label = scriptexecutionrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.ScriptExecutionRecord.Query().
//		Select(scriptexecutionrecord.FieldUserID).
//		Scan(ctx, &v)
func (serq *ScriptExecutionRecordQuery) Select(fields ...string) *ScriptExecutionRecordSelect {
	serq.ctx.Fields = append(serq.ctx.Fields, fields...)
	sbuild := &ScriptExecutionRecordSelect{ScriptExecutionRecordQuery: serq}
	sbuild.label = scriptexecutionrecord.Label
	sbuild.flds, sbuild.scan = &serq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScriptExecutionRecordSelect configured with the given aggregations.
func (serq *ScriptExecutionRecordQuery) Aggregate(fns ...AggregateFunc) *ScriptExecutionRecordSelect {
	return serq.Select().Aggregate(fns...)
}

func (serq *ScriptExecutionRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range serq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, serq); err != nil {
				return err
			}
		}
	}
	for _, f := range serq.ctx.Fields {
		if !scriptexecutionrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if serq.path != nil {
		prev, err := serq.path(ctx)
		if err != nil {
			return err
		}
		serq.sql = prev
	}
	return nil
}

func (serq *ScriptExecutionRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScriptExecutionRecord, error) {
	var (
		nodes       = []*ScriptExecutionRecord{}
		withFKs     = serq.withFKs
		_spec       = serq.querySpec()
		loadedTypes = [1]bool{
			serq.withScript != nil,
		}
	)
	if serq.withScript != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, scriptexecutionrecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScriptExecutionRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScriptExecutionRecord{config: serq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, serq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := serq.withScript; query != nil {
		if err := serq.loadScript(ctx, query, nodes, nil,
			func(n *ScriptExecutionRecord, e *Script) { n.Edges.Script = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (serq *ScriptExecutionRecordQuery) loadScript(ctx context.Context, query *ScriptQuery, nodes []*ScriptExecutionRecord, init func(*ScriptExecutionRecord), assign func(*ScriptExecutionRecord, *Script)) error {
	ids := make([]int32, 0, len(nodes))
	nodeids := make(map[int32][]*ScriptExecutionRecord)
	for i := range nodes {
		if nodes[i].script_script_execution_records == nil {
			continue
		}
		fk := *nodes[i].script_script_execution_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(script.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "script_script_execution_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (serq *ScriptExecutionRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := serq.querySpec()
	_spec.Node.Columns = serq.ctx.Fields
	if len(serq.ctx.Fields) > 0 {
		_spec.Unique = serq.ctx.Unique != nil && *serq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, serq.driver, _spec)
}

func (serq *ScriptExecutionRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scriptexecutionrecord.Table, scriptexecutionrecord.Columns, sqlgraph.NewFieldSpec(scriptexecutionrecord.FieldID, field.TypeInt32))
	_spec.From = serq.sql
	if unique := serq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if serq.path != nil {
		_spec.Unique = true
	}
	if fields := serq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptexecutionrecord.FieldID)
		for i := range fields {
			if fields[i] != scriptexecutionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := serq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := serq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := serq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := serq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (serq *ScriptExecutionRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(serq.driver.Dialect())
	t1 := builder.Table(scriptexecutionrecord.Table)
	columns := serq.ctx.Fields
	if len(columns) == 0 {
		columns = scriptexecutionrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if serq.sql != nil {
		selector = serq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if serq.ctx.Unique != nil && *serq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range serq.predicates {
		p(selector)
	}
	for _, p := range serq.order {
		p(selector)
	}
	if offset := serq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := serq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScriptExecutionRecordGroupBy is the group-by builder for ScriptExecutionRecord entities.
type ScriptExecutionRecordGroupBy struct {
	selector
	build *ScriptExecutionRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sergb *ScriptExecutionRecordGroupBy) Aggregate(fns ...AggregateFunc) *ScriptExecutionRecordGroupBy {
	sergb.fns = append(sergb.fns, fns...)
	return sergb
}

// Scan applies the selector query and scans the result into the given value.
func (sergb *ScriptExecutionRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sergb.build.ctx, "GroupBy")
	if err := sergb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScriptExecutionRecordQuery, *ScriptExecutionRecordGroupBy](ctx, sergb.build, sergb, sergb.build.inters, v)
}

func (sergb *ScriptExecutionRecordGroupBy) sqlScan(ctx context.Context, root *ScriptExecutionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sergb.fns))
	for _, fn := range sergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sergb.flds)+len(sergb.fns))
		for _, f := range *sergb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sergb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sergb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScriptExecutionRecordSelect is the builder for selecting fields of ScriptExecutionRecord entities.
type ScriptExecutionRecordSelect struct {
	*ScriptExecutionRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sers *ScriptExecutionRecordSelect) Aggregate(fns ...AggregateFunc) *ScriptExecutionRecordSelect {
	sers.fns = append(sers.fns, fns...)
	return sers
}

// Scan applies the selector query and scans the result into the given value.
func (sers *ScriptExecutionRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sers.ctx, "Select")
	if err := sers.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScriptExecutionRecordQuery, *ScriptExecutionRecordSelect](ctx, sers.ScriptExecutionRecordQuery, sers, sers.inters, v)
}

func (sers *ScriptExecutionRecordSelect) sqlScan(ctx context.Context, root *ScriptExecutionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sers.fns))
	for _, fn := range sers.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
