// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tntlinking-computeshare/computeshare-server/internal/data/ent/predicate"
	"github.com/tntlinking-computeshare/computeshare-server/internal/data/ent/storage"
)

// StorageUpdate is the builder for updating Storage entities.
type StorageUpdate struct {
	config
	hooks    []Hook
	mutation *StorageMutation
}

// Where appends a list predicates to the StorageUpdate builder.
func (_u *StorageUpdate) Where(ps ...predicate.Storage) *StorageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *StorageUpdate) SetOwner(v string) *StorageUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableOwner(v *string) *StorageUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StorageUpdate) SetType(v int32) *StorageUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableType(v *int32) *StorageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *StorageUpdate) AddType(v int32) *StorageUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StorageUpdate) SetName(v string) *StorageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableName(v *string) *StorageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCid sets the "cid" field.
func (_u *StorageUpdate) SetCid(v string) *StorageUpdate {
	_u.mutation.SetCid(v)
	return _u
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableCid(v *string) *StorageUpdate {
	if v != nil {
		_u.SetCid(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *StorageUpdate) SetSize(v int32) *StorageUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableSize(v *int32) *StorageUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *StorageUpdate) AddSize(v int32) *StorageUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetLastModify sets the "last_modify" field.
func (_u *StorageUpdate) SetLastModify(v time.Time) *StorageUpdate {
	_u.mutation.SetLastModify(v)
	return _u
}

// SetNillableLastModify sets the "last_modify" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableLastModify(v *time.Time) *StorageUpdate {
	if v != nil {
		_u.SetLastModify(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StorageUpdate) SetParentID(v string) *StorageUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StorageUpdate) SetNillableParentID(v *string) *StorageUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// Mutation returns the StorageMutation object of the builder.
func (_u *StorageUpdate) Mutation() *StorageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageUpdate) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := storage.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Storage.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := storage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Storage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cid(); ok {
		if err := storage.CidValidator(v); err != nil {
			return &ValidationError{Name: "cid", err: fmt.Errorf(`ent: validator failed for field "Storage.cid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentID(); ok {
		if err := storage.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Storage.parent_id": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storage.Table, storage.Columns, sqlgraph.NewFieldSpec(storage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(storage.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storage.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(storage.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cid(); ok {
		_spec.SetField(storage.FieldCid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(storage.FieldSize, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(storage.FieldSize, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.LastModify(); ok {
		_spec.SetField(storage.FieldLastModify, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(storage.FieldParentID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageUpdateOne is the builder for updating a single Storage entity.
type StorageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageMutation
}

// SetOwner sets the "owner" field.
func (_u *StorageUpdateOne) SetOwner(v string) *StorageUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableOwner(v *string) *StorageUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *StorageUpdateOne) SetType(v int32) *StorageUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableType(v *int32) *StorageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *StorageUpdateOne) AddType(v int32) *StorageUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StorageUpdateOne) SetName(v string) *StorageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableName(v *string) *StorageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCid sets the "cid" field.
func (_u *StorageUpdateOne) SetCid(v string) *StorageUpdateOne {
	_u.mutation.SetCid(v)
	return _u
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableCid(v *string) *StorageUpdateOne {
	if v != nil {
		_u.SetCid(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *StorageUpdateOne) SetSize(v int32) *StorageUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableSize(v *int32) *StorageUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *StorageUpdateOne) AddSize(v int32) *StorageUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetLastModify sets the "last_modify" field.
func (_u *StorageUpdateOne) SetLastModify(v time.Time) *StorageUpdateOne {
	_u.mutation.SetLastModify(v)
	return _u
}

// SetNillableLastModify sets the "last_modify" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableLastModify(v *time.Time) *StorageUpdateOne {
	if v != nil {
		_u.SetLastModify(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StorageUpdateOne) SetParentID(v string) *StorageUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StorageUpdateOne) SetNillableParentID(v *string) *StorageUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// Mutation returns the StorageMutation object of the builder.
func (_u *StorageUpdateOne) Mutation() *StorageMutation {
	return _u.mutation
}

// Where appends a list predicates to the StorageUpdate builder.
func (_u *StorageUpdateOne) Where(ps ...predicate.Storage) *StorageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageUpdateOne) Select(field string, fields ...string) *StorageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Storage entity.
func (_u *StorageUpdateOne) Save(ctx context.Context) (*Storage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageUpdateOne) SaveX(ctx context.Context) *Storage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageUpdateOne) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := storage.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Storage.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := storage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Storage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cid(); ok {
		if err := storage.CidValidator(v); err != nil {
			return &ValidationError{Name: "cid", err: fmt.Errorf(`ent: validator failed for field "Storage.cid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentID(); ok {
		if err := storage.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Storage.parent_id": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageUpdateOne) sqlSave(ctx context.Context) (_node *Storage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storage.Table, storage.Columns, sqlgraph.NewFieldSpec(storage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Storage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storage.FieldID)
		for _, f := range fields {
			if !storage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(storage.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(storage.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(storage.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cid(); ok {
		_spec.SetField(storage.FieldCid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(storage.FieldSize, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(storage.FieldSize, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.LastModify(); ok {
		_spec.SetField(storage.FieldLastModify, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(storage.FieldParentID, field.TypeString, value)
	}
	_node = &Storage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
