// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: compute/v1/computepower.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunPythonPackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid     string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *RunPythonPackageRequest) Reset() {
	*x = RunPythonPackageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compute_v1_computepower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunPythonPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonPackageRequest) ProtoMessage() {}

func (x *RunPythonPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_computepower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonPackageRequest.ProtoReflect.Descriptor instead.
func (*RunPythonPackageRequest) Descriptor() ([]byte, []int) {
	return file_compute_v1_computepower_proto_rawDescGZIP(), []int{0}
}

func (x *RunPythonPackageRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *RunPythonPackageRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunPythonPackageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *RunPythonPackageReply) Reset() {
	*x = RunPythonPackageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compute_v1_computepower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunPythonPackageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonPackageReply) ProtoMessage() {}

func (x *RunPythonPackageReply) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_computepower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonPackageReply.ProtoReflect.Descriptor instead.
func (*RunPythonPackageReply) Descriptor() ([]byte, []int) {
	return file_compute_v1_computepower_proto_rawDescGZIP(), []int{1}
}

func (x *RunPythonPackageReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type RunBenchmarksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunBenchmarksRequest) Reset() {
	*x = RunBenchmarksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compute_v1_computepower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBenchmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBenchmarksRequest) ProtoMessage() {}

func (x *RunBenchmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_computepower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBenchmarksRequest.ProtoReflect.Descriptor instead.
func (*RunBenchmarksRequest) Descriptor() ([]byte, []int) {
	return file_compute_v1_computepower_proto_rawDescGZIP(), []int{2}
}

type RunBenchmarksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *RunBenchmarksReply) Reset() {
	*x = RunBenchmarksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compute_v1_computepower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBenchmarksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBenchmarksReply) ProtoMessage() {}

func (x *RunBenchmarksReply) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_computepower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBenchmarksReply.ProtoReflect.Descriptor instead.
func (*RunBenchmarksReply) Descriptor() ([]byte, []int) {
	return file_compute_v1_computepower_proto_rawDescGZIP(), []int{3}
}

func (x *RunBenchmarksReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_compute_v1_computepower_proto protoreflect.FileDescriptor

var file_compute_v1_computepower_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a,
	0x17, 0x52, 0x75, 0x6e, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x50, 0x79, 0x74, 0x68, 0x6f,
	0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x75, 0x6e, 0x42, 0x65, 0x6e, 0x63,
	0x68, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a,
	0x12, 0x52, 0x75, 0x6e, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x9a, 0x02, 0x0a, 0x0c,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x86, 0x01, 0x0a,
	0x10, 0x52, 0x75, 0x6e, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x50,
	0x79, 0x74, 0x68, 0x6f, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x22, 0x17, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x70,
	0x79, 0x74, 0x68, 0x6f, 0x6e, 0x12, 0x80, 0x01, 0x0a, 0x0d, 0x52, 0x75, 0x6e, 0x42, 0x65, 0x6e,
	0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x42, 0x65, 0x6e, 0x63,
	0x68, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x75, 0x6e, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a, 0x22, 0x1a, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x62,
	0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x42, 0x39, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x25, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_compute_v1_computepower_proto_rawDescOnce sync.Once
	file_compute_v1_computepower_proto_rawDescData = file_compute_v1_computepower_proto_rawDesc
)

func file_compute_v1_computepower_proto_rawDescGZIP() []byte {
	file_compute_v1_computepower_proto_rawDescOnce.Do(func() {
		file_compute_v1_computepower_proto_rawDescData = protoimpl.X.CompressGZIP(file_compute_v1_computepower_proto_rawDescData)
	})
	return file_compute_v1_computepower_proto_rawDescData
}

var file_compute_v1_computepower_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_compute_v1_computepower_proto_goTypes = []interface{}{
	(*RunPythonPackageRequest)(nil), // 0: api.compute.v1.RunPythonPackageRequest
	(*RunPythonPackageReply)(nil),   // 1: api.compute.v1.RunPythonPackageReply
	(*RunBenchmarksRequest)(nil),    // 2: api.compute.v1.RunBenchmarksRequest
	(*RunBenchmarksReply)(nil),      // 3: api.compute.v1.RunBenchmarksReply
}
var file_compute_v1_computepower_proto_depIdxs = []int32{
	0, // 0: api.compute.v1.Computepower.RunPythonPackage:input_type -> api.compute.v1.RunPythonPackageRequest
	2, // 1: api.compute.v1.Computepower.RunBenchmarks:input_type -> api.compute.v1.RunBenchmarksRequest
	1, // 2: api.compute.v1.Computepower.RunPythonPackage:output_type -> api.compute.v1.RunPythonPackageReply
	3, // 3: api.compute.v1.Computepower.RunBenchmarks:output_type -> api.compute.v1.RunBenchmarksReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compute_v1_computepower_proto_init() }
func file_compute_v1_computepower_proto_init() {
	if File_compute_v1_computepower_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_compute_v1_computepower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunPythonPackageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compute_v1_computepower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunPythonPackageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compute_v1_computepower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBenchmarksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compute_v1_computepower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBenchmarksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compute_v1_computepower_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_v1_computepower_proto_goTypes,
		DependencyIndexes: file_compute_v1_computepower_proto_depIdxs,
		MessageInfos:      file_compute_v1_computepower_proto_msgTypes,
	}.Build()
	File_compute_v1_computepower_proto = out.File
	file_compute_v1_computepower_proto_rawDesc = nil
	file_compute_v1_computepower_proto_goTypes = nil
	file_compute_v1_computepower_proto_depIdxs = nil
}
